### PR TITLE
Fixes bug #1787 non-k8s: KubeArmor panics when not-enabled policy type is received

### LINKED ISSUE #1787: non-k8s: KubeArmor panics when not-enabled policy type is received
## Bug Report

**General Information**

- Environment description - Any environment
- Kernel version - Not relevant
- Orchestration system version in use - Not relevant

**To Reproduce**

1. Modify `make run` target in KubeArmor's Makefile to something like below such that host policy is disabled:
	```bash
	cd $(CURDIR); DEBUG=true sudo -E ./kubearmor -k8s=false -logPath=/tmp/kubearmor.log -enableKubeArmorPolicy -defaultFilePosture block -defaultCapabilitiesPosture block -defaultNetworkPosture block

	```
2. Once KubeArmor is running, send the below host policy by running `karmor vm policy --gRPC=:32767 add <path-to-policy>` :
	```yaml
    apiVersion: security.kubearmor.com/v1
    kind: KubeArmorHostPolicy
    metadata:
      name: hsp-block-sleep
    spec:
      severity: 10
      message: "sleep was attempted to be executed"
      tags:
      - ALERT
      nodeSelector:
        matchLabels:
          kubearmor.io/hostname: '*'
      process:
        matchPaths:
        - path: /usr/bin/sleep
      action:
        Block
	```
	
	You'll see that KubeArmor panics and dies with the below log:
	```
	     panic: runtime error: invalid memory address or nil pointer dereference
        [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x189052c]

        goroutine 424 [running]:
        github.com/kubearmor/KubeArmor/KubeArmor/policy.(*PolicyServer).HostPolicy(0xc00460c3c0, {0x1c94900?, 0xc0039e5990?}, 0xc003be38c0)
                /usr/src/KubeArmor/KubeArmor/policy/policy.go:62 +0xac
        github.com/kubearmor/KubeArmor/protobuf._PolicyService_HostPolicy_Handler({0x1c94900, 0xc00460c3c0}, {0x22822a8, 0xc00471ef60}, 0xc004689780, 0x0)
                /usr/src/KubeArmor/protobuf/policy_grpc.pb.go:203 +0x1a6
        google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022d200, {0x22822a8, 0xc00471eed0}, {0x228afa0, 0xc00472d080}, 0xc0048fe000, 0xc0046086c0, 0x335bd18, 0x0)
                /go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1369 +0xdf8
        google.golang.org/grpc.(*Server).handleStream(0xc00022d200, {0x228afa0, 0xc00472d080}, 0xc0048fe000)
                /go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1780 +0xe8b
        google.golang.org/grpc.(*Server).serveStreams.func2.1()
                /go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1019 +0x8b
        created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 436
                /go/pkg/mod/google.golang.org/grpc@v1.63.2/server.go:1030 +0x125

	```
	
Similar behavior is observed when container policy is disabled.

**Expected behavior**

KubeArmor should not panic and just log OR send back the response that policy enforcement for this `kind` (KubeArmorPolicy/KubeArmorHostPolicy) is not enabled.

### PR DESCRIPTION
**Pull request by itsCheithanya**
This fixes the bug that KubeArmor panics when not-enabled policy type is being received 
 **Reproduce the issue :**
Modify make run target in KubeArmor's Makefile to something like below such that host policy is disabled:

```
 cd $(CURDIR); DEBUG=true sudo -E ./kubearmor -k8s=false -logPath=/tmp/kubearmor.log -enableKubeArmorPolicy -defaultFilePosture block -defaultCapabilitiesPosture block -defaultNetworkPosture block 

```
Once KubeArmor is running, send the below host policy by running `karmor vm policy --gRPC=:32767 add <path-to-policy>` :
```

apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-block-sleep
spec:
  severity: 10
  message: "sleep was attempted to be executed"
  tags:
  - ALERT
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: '*'
  process:
    matchPaths:
    - path: /usr/bin/sleep
  action:
    Block
```
image
You'll see that KubeArmor doesn't panic :
image

Fixes #1787

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Bug fix. Fixes #1787 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

File: KubeArmor/policy/policy.go [hunk 1]
```diff
@@ -18,13 +18,19 @@ type PolicyServer struct {
 	pb.PolicyServiceServer
 	UpdateContainerPolicy func(tp.K8sKubeArmorPolicyEvent) pb.PolicyStatus
 	UpdateHostPolicy      func(tp.K8sKubeArmorHostPolicyEvent) pb.PolicyStatus
+	ContainerPolicyEnabled bool
+    HostPolicyEnabled      bool
```
Comment (DelusionalOptimist) [inline KubeArmor/policy/policy.go]: Please run gofmt.

File: KubeArmor/policy/policy.go [hunk 2]
```diff
@@ -18,13 +18,19 @@ type PolicyServer struct {
...
 }
 
 // ContainerPolicy accepts container events on gRPC and update container security policies
 func (p *PolicyServer) ContainerPolicy(c context.Context, data *pb.Policy) (*pb.Response, error) {
-	policyEvent := tp.K8sKubeArmorPolicyEvent{}
 	res := new(pb.Response)
-
+	if !p.ContainerPolicyEnabled {
+        res.Status = pb.PolicyStatus_Invalid
```
Comment (DelusionalOptimist) [inline KubeArmor/policy/policy.go]: Let's add a new status to the [Policy proto](https://github.com/kubearmor/KubeArmor/blob/main/protobuf/policy.proto) for this?
Maybe something along the name of `NotEnabled`?

File: KubeArmor/policy/policy.go [hunk 3]
```diff
@@ -50,9 +56,13 @@ func (p *PolicyServer) ContainerPolicy(c context.Context, data *pb.Policy) (*pb.
 
 // HostPolicy accepts host policy event on gRPC service and updates host security policies. It responds with 1 if success else 0.
 func (p *PolicyServer) HostPolicy(c context.Context, data *pb.Policy) (*pb.Response, error) {
-
-	policyEvent := tp.K8sKubeArmorHostPolicyEvent{}
 	res := new(pb.Response)
+	if (!p.HostPolicyEnabled) {
```
Comment (DelusionalOptimist) [inline KubeArmor/policy/policy.go]:
```suggestion
	if !p.HostPolicyEnabled {
```

**Review by DelusionalOptimist — CHANGES_REQUESTED** [review]
Thanks @itsCheithanya!
Minor changes to address... Looking good otherwise.

File: KubeArmor/policy/policy.go (hunk 2 above)
Comment (itsCheithanya) [reply KubeArmor/policy/policy.go]: I have done the required change @DelusionalOptimist

File: protobuf/policy.proto
Comment (DelusionalOptimist) [inline protobuf/policy.proto:1]: Did you build the code after adding this change?
Just try running `make build` once and you'll see come changes in `policy.pb.go` in the protobuf directory. Please add that as well.
And then you can use the generated constant in `pb.PolicyStatus_NotEnabled` in policy.go

File: KubeArmor/policy/policy.go [hunk 4]
```diff
@@ -50,9 +56,13 @@ func (p *PolicyServer) ContainerPolicy(c context.Context, data *pb.Policy) (*pb.
 
 // HostPolicy accepts host policy event on gRPC service and updates host security policies. It responds with 1 if success else 0.
 func (p *PolicyServer) HostPolicy(c context.Context, data *pb.Policy) (*pb.Response, error) {
-
-	policyEvent := tp.K8sKubeArmorHostPolicyEvent{}
 	res := new(pb.Response)
+	if !p.HostPolicyEnabled {
+		res.Status = pb.PolicyStatus_Invalid
```
Comment (DelusionalOptimist) [inline KubeArmor/policy/policy.go]:
```suggestion
		res.Status = pb.PolicyStatus_NotEnabled
```

**Review by DelusionalOptimist — CHANGES_REQUESTED** [review]
Thanks for addressing the changes.
Please see the comments inline @itsCheithanya

File: protobuf/policy.proto
Comment (itsCheithanya) [reply protobuf/policy.proto:1]: Ohh okay my bad missed that will do

Comment (itsCheithanya) [reply protobuf/policy.proto:1]: image
Getting `Policy 6` instead of `Policy NotEnabled` 
what could be the reason?

Comment (DelusionalOptimist) [reply protobuf/policy.proto:1]: Yes, @itsCheithanya once we merge this PR we'll need to update the `proto` package in kubearmor-client so that it can understand this error code.
For now it's fine, let's do it after we address all the changes and merge this PR.

Comment (Aryan-sharma11) [reply protobuf/policy.proto:1]: @itsCheithanya you have to build the client after updating the `github.com/kubearmor/KubeArmor/protobuf` dependecy in karmor client.

**Review by DelusionalOptimist — APPROVED** [review]
LGTM. Thanks @itsCheithanya! :rocket:
Please rebase with main so that we can merge.

Can you also do the changes required for handling this new error code in kubearmor-client?

**Review by daemon1024 — APPROVED** [review]

**Review by Aryan-sharma11 — APPROVED** [review]

**Comment by itsCheithanya** [comment]
> LGTM. Thanks @itsCheithanya! 🚀 Please rebase with main so that we can merge.
> 
> Can you also do the changes required for handling this new error code in kubearmor-client?

Sure will do that :)
