### PR TITLE
fix:(operator): Fix update functionality to recommend policies

### LINKED ISSUE #2086: Kubermor Operator fails to update the policies based on config state
## Bug Report
KubeArmor Operator fails to delete the recommended policies when recommend is set to false.
policyspec:
```yaml
Spec:
  Adapters:
    Elasticsearch:
      Auth:
  Alert Throttling:  true
  Kube Rbac Proxy Image:
    Image Pull Policy:  Always
  Kubearmor Controller Image:
    Image:              kubearmor/kubearmor-controller:stable
    Image Pull Policy:  Always
  Kubearmor Image:
    Image:              kubearmor/kubearmor:stable
    Image Pull Policy:  Always
  Kubearmor Init Image:
    Image:              kubearmor/kubearmor-init:stable
    Image Pull Policy:  Always
  Kubearmor Relay Image:
    Image:              kubearmor/kubearmor-relay-server:stable
    Image Pull Policy:  Always
  Max Alert Per Sec:    10
  Recommended Policies:
    Enable:      false
  Throttle Sec:  30
  Tls:
    Enable:  false
```

**General Information**

- Environment description: K3s
- Kernel version 6.11.0-26-generic 
- Orchestration system version in use 
(Client Version: v1.32.5+k3s1
Kustomize Version: v5.5.0
Server Version: v1.32.5+k3s1)

**To Reproduce**

1. Deploy kubearmor with `karmor install`
2. set the recommend policy as true by editing the kubearmorconfig crd.
`kubectl edit kubearmorconfigs.operator.kubearmor.com/kubearmorconfig-default  -n kubearmor`
3. Checking whether the recommended policies are working
4. Now set the recommend policies to false and see whether the policies are deleted. 

**Expected behavior**

Recommended policies should be deleted if recommend is set to false

**Screenshots**

Image

### PR DESCRIPTION
**Pull request by harisudarsan1**
**This PR fixes the update functionality for recommend policies**:

Fixes #2086 

**Does this PR introduce a breaking change?**
No

**Checklist:**
- [x] Bug fix. Fixes #2086 
- [] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

File: pkg/KubeArmorOperator/internal/controller/cluster.go [hunk 1]
```diff
@@ -1250,13 +1250,18 @@ func (clusterWatcher *ClusterWatcher) WatchRecommendedPolicies() error {
...
+				if pol, err := clusterWatcher.Secv1Client.SecurityV1().KubeArmorClusterPolicies().Get(context.Background(), csp.Name, v1.GetOptions{}); err == nil &&
+					pol.Annotations["app.kubernetes.io/managed-by"] == "kubearmor-operator" {
+					err = clusterWatcher.Secv1Client.SecurityV1().KubeArmorClusterPolicies().Delete(context.Background(), csp.GetName(), metav1.DeleteOptions{})
+					if err != nil && !metav1errors.IsNotFound(err) {
+						clusterWatcher.Log.Warnf("error deleting csp %s", csp.GetName())
+						continue
+					} else if err == nil {
+						clusterWatcher.Log.Infof("deleted csp %s", csp.GetName())
+					}
+				} else if err != nil && !metav1errors.IsNotFound(err) {
```
Comment (rootxrishabh) [inline pkg/KubeArmorOperator/internal/controller/cluster.go:1263]: line 1257 has the same condition

**Review by rootxrishabh — CHANGES_REQUESTED** [review]

File: pkg/KubeArmorOperator/internal/controller/cluster.go (hunk 1 above)
Comment (rootxrishabh) [reply pkg/KubeArmorOperator/internal/controller/cluster.go:1263]: NVM, this is for another block

**Review by rootxrishabh — APPROVED** [review]

**Review by Aryan-sharma11 — APPROVED** [review]
Tested locally, working as expected. LGTM
