### PR TITLE
fix(core): handle bpf as an exception for setting node annotations

### LINKED ISSUE #1765: Host Security Policy not enforced
## Bug Report

**General Information**

- Environment description: k3s
- Kernel version (run `uname -a`):
```
Linux thunderbird 6.9.1-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 17 May 2024 16:56:38 +0000 x86_64 GNU/Linux
```
- Orchestration system version in use (e.g. `kubectl version`, ...)
```
Client Version: v1.30.1
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.4+k3s1
```
- Link to relevant artifacts (policies, deployments scripts, ...)
Used KubeArmorHostPolicy
```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: hsp-thunderbird
spec:
  nodeSelector:
    matchLabels:
      kubernetes.io/os: linux
  process:
    matchPaths:
    - path: /usr/bin/pacman
    - path: /usr/bin/sleep
  action:
    Block
```
- Target containers/pods
N/A

**To Reproduce**

1. Started a k3s cluster using
```
curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE="644" INSTALL_K3S_EXEC="--disable=traefik --docker --container-runtime-endpoint unix:///var/run/docker.sock --kubelet-arg cgroup-driver=systemd" sh -
```
2. Installed KubeArmor using
```
helm upgrade --install kubearmor-operator kubearmor/kubearmor-operator -n kubearmor --create-namespace
helm upgrade --install kubearmor kubearmor/kubearmor -n kubearmor --create-namespace 
```
3. Enabled Host Visbility by editing the kubearmor daemonset ([ref](https://docs.kubearmor.io/kubearmor/documentation/faq#how-to-enable-kubearmorhostpolicy-for-k8s-cluster))
```
kubectl edit daemonsets.apps -n kubearmor kubearmor
#####
    spec:
      containers:
      - args:
        - -gRPC=32767
+       - -enableKubeArmorHostPolicy
+       - -hostVisibility=process,file,network,capabilities
#####
```

4. Annotated the node using
```
kubectl annotate node thunderbird "kubearmor-visibility=process,file,network,capabilities"
```

5. Confirmed both of them (Step 3 and Step 4) are using 
```
$ kubectl logs -n kubearmor pod/kubearmor-jz644 | grep "Started to protect"
Defaulted container "kubearmor" out of: kubearmor, init (init)
2024-05-23 16:11:50.482130      INFO     Started to protect a host and containers
```
and
```
$ kubectl describe node thunderbird | grep kubearmor-visibility
                    kubearmor-visibility: process,file,network,capabilities
```

6. Applied the above mentioned policy using `kubectl apply -f`

7. Ran the commands mentioned in the policy
```
$ sleep                           
sleep: missing operand
Try 'sleep --help' for more information.
$ pacman
error: no operation specified (use -h for help)
```
**Expected behavior**

The execution of command `pacman` and `sleep` should be blocked and shown as ```Permission denied
command terminated with exit code 126```

**Additional Info**

1. When checking the logs after applying the policy using `k logs kubearmor-jz644 -n kubearmor`, it shows 
```
2024-05-24 00:28:03.149172      INFO     Detected a Host Security Policy (modified/hsp-thunderbird)
```
I t detects the policy but does not update it. In case of container enforcement, we see the following logs
```
2024-05-23 16:19:02.822584      INFO     Detected a Security Policy (added/default/ksp-nginx)
2024-05-23 16:19:02.822651      INFO     Updating container rules for 404efd73a323f7644c882ff037be71e17c9c05d7a65008f0d6a31f25791a14f3
```
2. Output from `karmor probe`
```
$ karmor probe                       

Found KubeArmor running in Kubernetes

Daemonset :
     kubearmor       Desired: 1      Ready: 1        Available: 1    
Deployments : 
     kubearmor-operator      Desired: 1      Ready: 1        Available: 1    
        kubearmor-relay         Desired: 1      Ready: 1        Available: 1    
        kubearmor-controller    Desired: 1      Ready: 1        Available: 1    
Containers : 
     kubearmor-operator-5878ff8b8b-gkqk8     Running: 1      Image Version: kubearmor/kubearmor-operator:v1.3.4      
        kubearmor-relay-85646db78c-zqnvj        Running: 1      Image Version: kubearmor/kubearmor-relay-server:latest  
        kubearmor-controller-78b5859c9f-8tjk4   Running: 2      Image Version: kubearmor/kubearmor-controller:latest    
        kubearmor-jz644                         Running: 1      Image Version: kubearmor/kubearmor:stable               
Node 1 : 
     OS Image:                       Arch Linux                               
        Kernel Version:                 6.9.1-arch1-1                            
        Kubelet Version:                v1.29.4+k3s1                             
        Container Runtime:              docker://26.1.3                          
        Active LSM:                     BPFLSM                                   
        Host Security:                  true                                     
        Container Security:             true                                     
        Container Default Posture:      audit(File)                          audit(Capabilities)  audit(Network)       
        Host Default Posture:           audit(File)                          audit(Capabilities)  audit(Network)       
        Host Visibility:                process,file,network,capabilities        
Armored Up pods : 
+-----------+--------------------------------+-----------------------------------+------------------------+-----------+
| NAMESPACE |        DEFAULT POSTURE         |            VISIBILITY             |          NAME          |  POLICY   |
+-----------+--------------------------------+-----------------------------------+------------------------+-----------+
| default   | File(audit),                   | process,file,network,capabilities | nginx-7854ff8877-7pzvx | ksp-nginx |
|           | Capabilities(audit), Network   |                                   |                        |           |
|           | (audit)                        |                                   |                        |           |
+-----------+--------------------------------+-----------------------------------+------------------------+-----------+
```
3. Container Enforcement is working. Running apt on mentioned nginx pod gives
```
kubectl exec -it $POD -- bash -c "apt update && apt install masscan"     
bash: line 1: /usr/bin/apt: Permission denied
command terminated with exit code 126
```

4. `karmor logs --logFilter=all` shows HostLogs
5. Path of both `pacman` and `sleep` is correct

### PR DESCRIPTION
**Pull request by tesla59**
**Purpose of PR?**:

Fixes #1765 

**Does this PR introduce a breaking change?**
No

**If the changes in this PR are manually verified, list down the scenarios covered:**:
In progress (draft PR)

**Additional information for reviewer?** :
No

**Checklist:**
- [x] Bug fix. Fixes #1765 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

File: KubeArmor/core/kubeUpdate.go [hunk 1]
```diff
@@ -44,14 +44,18 @@ func (dm *KubeArmorDaemon) HandleNodeAnnotations(node *tp.Node) {
 	}
 
 	if lsm, err := os.ReadFile("/sys/kernel/security/lsm"); err == nil {
-		if !strings.Contains(string(lsm), "apparmor") && !strings.Contains(string(lsm), "selinux") {
-			// exception: neither AppArmor nor SELinux
+		hasAppArmor := strings.Contains(string(lsm), "apparmor")
+		hasSelinux := strings.Contains(string(lsm), "selinux")
+		hasBPF := strings.Contains(string(lsm), "bpf")
+
+		if !hasBPF && !hasSelinux && !hasAppArmor {
```
Comment (DelusionalOptimist) [inline KubeArmor/core/kubeUpdate.go]: @tesla59 this logic looks good. :heavy_check_mark: 
Just one more point - in Kubernetes mode, if KubeArmor is installed using operator the node will have a `kubearmor.io/enforcer` annotation which is applied by the operator. This contains the enforcer that has to be used.
So can we have a condition like
Check the `kubearmor.io/enforcer` annotation; if it is present, get enforcer from it else get enforcer using the LSM file. I think we should be good then.

Comment (tesla59) [reply KubeArmor/core/kubeUpdate.go]: added a check for `kubearmor.io/enforcer` annotation

**Comment by tesla59** [comment]
@DelusionalOptimist i have updated the logic to check for annotation. its ready to review
also rebased to main

File: KubeArmor/core/kubeUpdate.go [hunk 2]
```diff
@@ -48,19 +48,35 @@ func (dm *KubeArmorDaemon) HandleNodeAnnotations(node *tp.Node) {
...
+	var err error
+
+	// Check if enforcer is set in the node annotations
+	if v, ok := node.Annotations["kubearmor.io/enforcer"]; ok {
+		lsm = []byte(v)
+	} else { // Read the lsm from the system
+		lsm, err = os.ReadFile("/sys/kernel/security/lsm")
+		if err != nil {
+			kg.Errf("Failed to read /sys/kernel/security/lsm (%s)", err)
+		}
```
Comment (DelusionalOptimist) [inline KubeArmor/core/kubeUpdate.go]: Everything looks good.
Small NIT: Instead of doing string conversion again and again we can make `lsm` object string and convert the `byteData` to string after reading from file. Also, some error handling if lsm file is empty:

```suggestion
		lsmByteData, err = os.ReadFile("/sys/kernel/security/lsm")
		if err != nil {
			kg.Errf("Failed to read /sys/kernel/security/lsm (%s)", err)
		} else if len(lsmByteData) == 0 {
     kg.Errf("Failed to read /sys/kernel/security/lsm: empty file")
   }

   lsm = string(lsmByteData)
```

**Comment by tesla59** [comment]
@DelusionalOptimist added error handling for empty lsm file and also refactored byte->string conversion (and vice-versa) logic

**Review by Aryan-sharma11 — DISMISSED** [review]

File: KubeArmor/core/kubeUpdate.go [hunk 3]
```diff
@@ -48,19 +48,37 @@ func (dm *KubeArmorDaemon) HandleNodeAnnotations(node *tp.Node) {
...
+	// == LSM == //
+	var lsm string
+
+	// Check if enforcer is set in the node annotations
+	if v, ok := node.Annotations["kubearmor.io/enforcer"]; ok {
+		lsm = v
+	} else { // Read the lsm from the system
+		lsmByteData, err := os.ReadFile("/sys/kernel/security/lsm")
+		if err != nil {
+			kg.Errf("Failed to read /sys/kernel/security/lsm (%s)", err)
```
Comment (DelusionalOptimist) [inline KubeArmor/core/kubeUpdate.go]: Minor changes based on operator changes introduced in the latest release.
```suggestion
	if v, ok := node.Labels["kubearmor.io/enforcer"]; ok {
		lsm = v
	} else { // Read the lsm from the system
		lsmByteData, err := os.ReadFile("/sys/kernel/security/lsm")
		if err != nil && !os.IsNotExist(err) {
			kg.Errf("Failed to read /sys/kernel/security/lsm (%s)", err.Error())
```

**Review by DelusionalOptimist — APPROVED** [review]
LGTM! Thanks for seeing this through @tesla59 :rocket:

**Review by daemon1024 — APPROVED** [review]

**Comment by DelusionalOptimist** [comment]
CRI-O test failing due to upstream issues. Irrelevant to the changes here.
