### PR TITLE
fix(core): fix to prevent policies from being applied to containers t…

### LINKED ISSUE #1387: Overwriting of security policies in `opt/kubearmor/policy`
## Bug Report

**General Information**

- Environment description :-  Kubearmor in systemd mode 
- Kernel version (run `uname -a`) : NA
- Orchestration system version in use (e.g. `kubectl version`, ...) : NA

**To Reproduce**

1. Instruction 1 : Run kubearmor in sytemd mode and apply policy on a container using `karmor vm policy add <policyname>` 
3. Instruction 2: Change the container name in policy and again apply it. Now if u list/read the policies under /opt/kubearmor/policy the policy applied earlier is now overwritten, while the policy is applied on both the containers.

**Expected behavior**

The policy applied on the previous container should be deleted. This scenario is handled in kubernetes environment but not in unorchestrated mode  .

### PR DESCRIPTION
**Pull request by haytok**
…hat shouldn't be applied

In running KubeArmor in systemd mode, when the container name (the value of `kubearmor.io/container.name`) in the applied policy was changed and the policy was applied, there was an issue where that policy was applied not only to the new container but also to the previous container.

This bug was also reported in issue/#1387.

Therefore, in this commit, the policy doesn't apply to the previous container, and apply to the new container.

**Purpose of PR?**:

Fixes #1387

**Does this PR introduce a breaking change?**

No

**If the changes in this PR are manually verified, list down the scenarios covered:**:

Based on the two tests below, I'll  show that this commit has been made to prevent the policy from being applied to containers that should not have been applied. 

### Note

I confirmed that the bug has been fixed by writing a debug program to check `dm.Endpoints` in the following part of [parseAndUpdateContainerSecurityPolicy()](https://github.com/kubearmor/KubeArmor/blob/main/KubeArmor/core/unorchestratedUpdates.go#L83C1-L546C2). 

https://github.com/kubearmor/KubeArmor/blob/main/KubeArmor/core/unorchestratedUpdates.go#L545

<details>
<summary> Debug code </summary>

```golang
ubuntu ~/KubeArmor/KubeArmor [fixed-not-to-overwrite-policies-already-applied]
> git diff core/unorchestratedUpdates.go
diff --git a/KubeArmor/core/unorchestratedUpdates.go b/KubeArmor/core/unorchestratedUpdates.go
index 1e87c341..b78c562d 100644
--- a/KubeArmor/core/unorchestratedUpdates.go
+++ b/KubeArmor/core/unorchestratedUpdates.go
@@ -5,6 +5,7 @@ package core

 import (
        "encoding/json"
+       "fmt"
        "os"
        "sort"
        "strings"
@@ -564,6 +565,10 @@ func (dm *KubeArmorDaemon) ParseAndUpdateContainerSecurityPolicy(event tp.K8sKub
                        dm.removeBackUpPolicy(secPolicy.Metadata["policyName"])
                }
        }
+
+       for i, endPoint := range dm.EndPoints {
+               fmt.Printf("i: %d, EndPointName: %s, number of policies: %d\n", i, endPoint.EndPointName, len(endPoint.SecurityPolicies))
+       }
 }

 // ================================= //
```

</details>

### Test case 1

1. Create `block_diff.yaml`

<details>
<summary> block_diff.yaml  </summary>

```yaml
ubuntu ~
> cat block_diff.yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-diff
spec:
  selector:
    matchLabels:
      # policyName
      kubearmor.io/container.name: hoge
  process:
    matchPaths:
      - path: /usr/bin/diff
  action:
    Block
```

</details>

2. apply `block_diff.yaml` by runnig `karmor vm policy add block_diff.yaml`

3. `dm.EndPoints` from debug message are shown below.

```bash
Sep 09 05:14:09 ip-172-31-33-167 kubearmor[377347]: 2023-09-09 05:14:09.880226        INFO        Detected a Container Security Policy (added/container_namespace/block-diff)
Sep 09 05:14:09 ip-172-31-33-167 kubearmor[377347]: 2023-09-09 05:14:09.903867        INFO        Registered the AppArmor profile (kubearmor_hoge)
Sep 09 05:14:09 ip-172-31-33-167 kubearmor[377347]: 2023-09-09 05:14:09.929617        INFO        Updated 1 security rule(s) to container_namespace/hoge/kubearmor_hoge
Sep 09 05:14:09 ip-172-31-33-167 kubearmor[377347]: i: 0, EndPointName: hoge, number of policies: 1
```

4. Update below `kubearmor.io/container.name` of `block_diff.yaml` and apply the policy

<details>
<summary> block_diff.yaml  </summary>

```yaml
ubuntu ~
> cat block_diff.yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-diff
spec:
  selector:
    matchLabels:
      # policyName
      kubearmor.io/container.name: fuga
  process:
    matchPaths:
      - path: /usr/bin/diff
  action:
    Block
```

</details>

5. `dm.EndPoints` are shown below.

```bash
Sep 09 05:14:37 ip-172-31-33-167 kubearmor[377347]: 2023-09-09 05:14:37.767391        INFO        Detected a Container Security Policy (added/container_namespace/block-diff)
Sep 09 05:14:37 ip-172-31-33-167 kubearmor[377347]: 2023-09-09 05:14:37.791037        INFO        Registered the AppArmor profile (kubearmor_fuga)
Sep 09 05:14:37 ip-172-31-33-167 kubearmor[377347]: 2023-09-09 05:14:37.816894        INFO        Updated 1 security rule(s) to container_namespace/fuga/kubearmor_fuga
Sep 09 05:14:37 ip-172-31-33-167 kubearmor[377347]: i: 0, EndPointName: fuga, number of policies: 1
```

From results of 5, the policy doesn't apply to the previous container, and apply to the new container.

Note that when the modifications due to this commit have not been changed, the following debug message will be output when the policy is applied in the above flow. 

```bash
Sep 09 05:10:05 ip-172-31-33-167 kubearmor[376347]: 2023-09-09 05:10:05.317470        INFO        Detected a Container Security Policy (added/container_namespace/block-diff)
Sep 09 05:10:05 ip-172-31-33-167 kubearmor[376347]: 2023-09-09 05:10:05.341019        INFO        Registered the AppArmor profile (kubearmor_hoge)
Sep 09 05:10:05 ip-172-31-33-167 kubearmor[376347]: 2023-09-09 05:10:05.367571        INFO        Updated 1 security rule(s) to container_namespace/hoge/kubearmor_hoge
Sep 09 05:10:05 ip-172-31-33-167 kubearmor[376347]: i: 0, EndPointName: hoge, number of policies: 1

# update container name
Sep 09 05:10:21 ip-172-31-33-167 kubearmor[376347]: 2023-09-09 05:10:21.261441        INFO        Detected a Container Security Policy (added/container_namespace/block-diff)
Sep 09 05:10:21 ip-172-31-33-167 kubearmor[376347]: 2023-09-09 05:10:21.284971        INFO        Registered the AppArmor profile (kubearmor_fuga)
Sep 09 05:10:21 ip-172-31-33-167 kubearmor[376347]: 2023-09-09 05:10:21.332505        INFO        Updated 1 security rule(s) to container_namespace/fuga/kubearmor_fuga
Sep 09 05:10:21 ip-172-31-33-167 kubearmor[376347]: i: 0, EndPointName: hoge, number of policies: 1
Sep 09 05:10:21 ip-172-31-33-167 kubearmor[376347]: i: 1, EndPointName: fuga, number of policies: 1
```

---

### Test case 2

1. Create  three policy files (`block_diff.yaml`, `block_ls.yaml`, `block_sleep.yaml`)

<details>
<summary> block_diff.yaml, block_ls.yaml, and block_sleep.yaml  </summary>

```yaml
ubuntu ~
> cat block_diff.yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-diff
spec:
  selector:
    matchLabels:
      # policyName
      kubearmor.io/container.name: hoge
  process:
    matchPaths:
      - path: /usr/bin/diff
  action:
    Block
ubuntu ~
> cat block_ls.yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-ls
spec:
  selector:
    matchLabels:
      # policyName
      kubearmor.io/container.name: hoge
  process:
    matchPaths:
      - path: /usr/bin/ls
  action:
    Block
ubuntu ~
> cat block_sleep.yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-sleep
spec:
  selector:
    matchLabels:
      # policyName
      kubearmor.io/container.name: hoge
  process:
    matchPaths:
      - path: /usr/bin/sleep
  action:
    Block
```

</details>

2. apply `block_diff.yaml` and `block_ls.yaml`

3. `dm.EndPoints` are shown below.

```bash
Sep 09 05:16:39 ip-172-31-33-167 kubearmor[377481]: 2023-09-09 05:16:39.844018        INFO        Detected a Container Security Policy (added/container_namespace/block-diff)
Sep 09 05:16:39 ip-172-31-33-167 kubearmor[377481]: 2023-09-09 05:16:39.867626        INFO        Registered the AppArmor profile (kubearmor_hoge)
Sep 09 05:16:39 ip-172-31-33-167 kubearmor[377481]: 2023-09-09 05:16:39.893401        INFO        Updated 1 security rule(s) to container_namespace/hoge/kubearmor_hoge
Sep 09 05:16:39 ip-172-31-33-167 kubearmor[377481]: i: 0, EndPointName: hoge, number of policies: 1


Sep 09 05:16:48 ip-172-31-33-167 kubearmor[377481]: 2023-09-09 05:16:48.835678        INFO        Detected a Container Security Policy (added/container_namespace/block-ls)
Sep 09 05:16:48 ip-172-31-33-167 kubearmor[377481]: 2023-09-09 05:16:48.862113        INFO        Updated 2 security rule(s) to container_namespace/hoge/kubearmor_hoge
Sep 09 05:16:48 ip-172-31-33-167 kubearmor[377481]: i: 0, EndPointName: hoge, number of policies: 2
```

4. Update below `kubearmor.io/container.name` of `block_diff.yaml`.

The container name in `block_diff.yaml` was changed from `hoge` to `fuga`, and apply the policy.

5. `dm.EndPoints` are shown below.

```bash
Sep 09 05:18:01 ip-172-31-33-167 kubearmor[377481]: 2023-09-09 05:18:01.761718        INFO        Detected a Container Security Policy (added/container_namespace/block-diff)
Sep 09 05:18:01 ip-172-31-33-167 kubearmor[377481]: 2023-09-09 05:18:01.785688        INFO        Registered the AppArmor profile (kubearmor_fuga)
Sep 09 05:18:01 ip-172-31-33-167 kubearmor[377481]: 2023-09-09 05:18:01.811592        INFO        Updated 1 security rule(s) to container_namespace/fuga/kubearmor_fuga
Sep 09 05:18:01 ip-172-31-33-167 kubearmor[377481]: i: 0, EndPointName: hoge, number of policies: 1
Sep 09 05:18:01 ip-172-31-33-167 kubearmor[377481]: i: 1, EndPointName: fuga, number of policies: 1
```

4. Update `kubearmor.io/container.name` of `block_ls.yaml`.

The container name in `block_ls.yaml` was changed from `hoge` to `fuga`, and apply the policy.

5. `dm.EndPoints` are shown below.

```bash
Sep 09 05:18:20 ip-172-31-33-167 kubearmor[377481]: 2023-09-09 05:18:20.732560        INFO        Detected a Container Security Policy (added/container_namespace/block-ls)
Sep 09 05:18:20 ip-172-31-33-167 kubearmor[377481]: 2023-09-09 05:18:20.759344        INFO        Updated 2 security rule(s) to container_namespace/fuga/kubearmor_fuga
Sep 09 05:18:20 ip-172-31-33-167 kubearmor[377481]: i: 0, EndPointName: fuga, number of policies: 2
```

6. apply `block_sleep.yaml`

7. `dm.EndPoints` are shown below.

```bash
Sep 09 05:18:44 ip-172-31-33-167 kubearmor[377481]: 2023-09-09 05:18:44.382272        INFO        Detected a Container Security Policy (added/container_namespace/block-sleep)
Sep 09 05:18:44 ip-172-31-33-167 kubearmor[377481]: 2023-09-09 05:18:44.408475        INFO        Updated 1 security rule(s) to container_namespace/hoge/kubearmor_hoge
Sep 09 05:18:44 ip-172-31-33-167 kubearmor[377481]: i: 0, EndPointName: fuga, number of policies: 2
Sep 09 05:18:44 ip-172-31-33-167 kubearmor[377481]: i: 1, EndPointName: hoge, number of policies: 1
```

8. Update `kubearmor.io/container.name` of `block_sleep.yaml`.

The container name in `block_sleep.yaml` was changed from `hoge` to `fuga`, and apply the policy.

9. `dm.EndPoints` are shown below.

```bash
Sep 09 05:19:03 ip-172-31-33-167 kubearmor[377481]: 2023-09-09 05:19:03.104947        INFO        Detected a Container Security Policy (added/container_namespace/block-sleep)
Sep 09 05:19:03 ip-172-31-33-167 kubearmor[377481]: 2023-09-09 05:19:03.131804        INFO        Updated 3 security rule(s) to container_namespace/fuga/kubearmor_fuga
Sep 09 05:19:03 ip-172-31-33-167 kubearmor[377481]: i: 0, EndPointName: fuga, number of policies: 3
```

From all results, the policy doesn't apply to the previous container, and apply to the new container.

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [x] Bug fix. Fixes #1387
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Review by daemon1024 — APPROVED** [review]
LGTM 🙌 Thanks a lot for the PR. We are in the process of fixing our CI we will start merging PRs then.

**Comment by haytok** [comment]
Thanks for the review.
I am happy to fix the bug :)

**Review by Aryan-sharma11 — CHANGES_REQUESTED** [review]
@haytok  Thanks for the PR, I tried it locally but still the policy is being enforced on the previous container as well. Imo simply updating the endpoint won't work as we need to update the container rules for the previous container too.
You can also test it locally by executing in the previous and the new container and running the commands.
For instance I have taken wordpress docker image from [here](https://github.com/docker/awesome-compose/tree/master/wordpress-mysql) 
and applied the Policy 
```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-block-policy
spec:
  severity: 3
  selector:
    matchLabels:
      kubearmor.io/container.name: wordpress-mysql-wordpress-1
  process:
    matchPaths:
    - path: /usr/bin/apt
    - path: /usr/bin/apt-get

      # apt update
      # apt-get update

  action:
    Block
```
-try executing in the contanier and run  commands `apt and apt update` they should be denied

- And now update the container name to  `wordpress-mysql-db-1` 
- Apply the policy and run the commands by  executing in the containers.  It is being denied in both the containers.  This should not be the case instead enforcement should be done only on `wordpress-mysql-db-1`

cc:- @daemon1024

**Comment by haytok** [comment]
Thanks for the review.

I will check it out.

**Comment by haytok** [comment]
Hi, @Aryan-sharma11 (cc: @daemon1024)

In the current implementation in systemd mode, [ParseAndUpdateContainerSecurityPolicy()](https://github.com/kubearmor/KubeArmor/blob/main/KubeArmor/core/unorchestratedUpdates.go#L83C28-L83C65) only seems to have the ability to create/modify/delete AppArmor profiles.

Therefore, it seems to be no feature to control containers that do not have an AppArmor profile specified in `--security-opt` of `docker run`, even if the container has a name specified in `kubearmor.io/container.name`. (ref: Verification 1 and 2)

Therefore, I have questions regarding reply from Aryan-sharma11.

1. Could you please provide details of the steps Aryan-sharma11 took to confirm the issue?
2. Could you please tell me how the issue was eventually resolved?

As for 2, even if you change the container name in KubeArmorPolicy after starting the container with the AppArmor profile specified in `--security-opt` of `docker run`, the limitation of commands that can be executed in the container is determined at startup, so it is assumed to be the same. 

In addition, I would like to note what I have verified on my end in response to Aryan-sharma11's reply.

## Verification 1

<details>
<summary> Detail </summary>

Create a policy (`ksp-block-policy.yaml`) with the following contents and apply it with `karmor vm policy add ksp-block-policy.yaml`.

```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-block-policy
spec:
  severity: 3
  selector:
    matchLabels:
      kubearmor.io/container.name: foo
  process:
    matchPaths:
    - path: /usr/bin/apt
    - path: /usr/bin/apt-get

      # apt update
      # apt-get update

  action:
    Block
```

Then, start a container named `foo`.

```bash
ubuntu ~
> docker run --rm \
>   --name foo \
>   -it php:8.0-apache bash
root@efc281e91de2:/var/www/html# apt update
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
...
```

Although the above Policy is applied, the `apt update` command can be executed in this container. This is expected behavior, so being able to run `apt get` even if you change the container name of the policy name is expected behavior. 

To apply a security policy to a container, you must specify `--security-opt` when `docker run`.

- [KubeArmor to protect IoT Edge containerized workloads](https://github.com/kubearmor/KubeArmor/wiki/KubeArmor-to-protect-IoT-Edge-containerized-workloads#apply-the-apparmor-profile-to-the-desired-container)

> Apply the apparmor profile to the desired container
>
> To run a container with KubeArmor enforcement using the apparmor profile kubearmor_homeassistant, pass --security-opt apparmor=kubearmor_homeassistant with the docker run command or if using docker-compose add:security_opts: apparmor=kubearmor_homeassistant under the container name in the docker-compose.yaml.

</details>

## Verification 2

<details>
<summary> Detail </summary>

Create a policy (`ksp-block-policy.yaml`) with the following contents and apply it with `karmor vm policy add ksp-block-policy.yaml`.

```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-block-policy
spec:
  severity: 3
  selector:
    matchLabels:
      kubearmor.io/container.name: foo
  process:
    matchPaths:
    - path: /usr/bin/apt
    - path: /usr/bin/apt-get

      # apt update
      # apt-get update

  action:
    Block
```

Start the container with the AppArmor profile created by the applied policy specified in `--security-opt`.

```bash
docker run --rm \
  --name foo \
  --security-opt apparmor=kubearmor_foo \
  -it php:8.0-apache bash
```

If you execute the `apt update` command in the container thus launched, it will be `Permission denied` and you will not be able to execute it.

Change `kubearmor.io/container.name` from `foo` to `bar` in the policy (`ksp-block-policy.yaml`) with the following contents and apply the change by `karmor vm policy add ksp-block-policy.yaml`. Apply the changes with `karmor vm policy add ksp-block-policy.yaml`.

```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-block-policy
spec:
  severity: 3
  selector:
    matchLabels:
      kubearmor.io/container.name: bar
  process:
    matchPaths:
    - path: /usr/bin/apt
    - path: /usr/bin/apt-get

      # apt update
      # apt-get update

  action:
    Block
```

If you run `apt update` in the container you just started in this state, you will get an error. This is expected behavior since the AppArmor profile before this change is specified in `--security-opt` of `docker run` when the container is started.

</details>

**Comment by haytok** [comment]
Hi, @Aryan-sharma11 

I understand Aryan-sharma11's review.

I need to fix so that not only `dm.EndPoints` but also `AppArmor profile` for the old container name is disabled.
Therefore, I will make the changes you reviewed and push.

Note that please feel free to ignore the Question in my comment above.

**Comment by Aryan-sharma11** [comment]
> Hi, @Aryan-sharma11
> 
> I understand Aryan-sharma11's review.
> 
> I need to fix so that not only `dm.EndPoints` but also `AppArmor profile` for the old container name is disabled. Therefore, I will make the changes you reviewed and push.
> 
> Note that please feel free to ignore the Question in my comment above.

@haytok Yes.  For reference, you can check out how we handle Policy [deletion](https://github.com/kubearmor/KubeArmor/blob/main/KubeArmor/core/unorchestratedUpdates.go#L529C1-L530C1) events.
And for testing purposes can you please test it with BPFLSM?

**Comment by haytok** [comment]
@Aryan-sharma11 

> For reference, you can check out how we handle Policy [deletion](https://github.com/kubearmor/KubeArmor/blob/main/KubeArmor/core/unorchestratedUpdates.go#L529C1-L530C1) events.

Thanks !!! I will fix for your reference.

>  And for testing purposes can you please test it with BPFLSM?

Sure. At this time, LSM on developing environment is `AppArmor`, but I will prepare the `BPF-LSM` environment as well to check the operation.

File: KubeArmor/core/unorchestratedUpdates.go [hunk 1]
```diff
@@ -503,6 +523,12 @@ func (dm *KubeArmorDaemon) ParseAndUpdateContainerSecurityPolicy(event tp.K8sKub
 			// add the endpoint into the endpoint list
 			dm.EndPoints = append(dm.EndPoints, newPoint)
 		} else {
+			for idx, endPoint := range dm.EndPoints {
+				if kl.MatchIdentities(secPolicy.Spec.Selector.Identities, endPoint.Identities) {
```
Comment (Aryan-sharma11) [inline KubeArmor/core/unorchestratedUpdates.go]: Is there a reason to do this step again, as we have already updated value of `i` above at [line](https://github.com/kubearmor/KubeArmor/pull/1406/files#diff-168b945c99cdc3669f72461c0f4913020872a0e7ff4222676b356125676a4c64R431)?

File: KubeArmor/core/unorchestratedUpdates.go [hunk 2]
```diff
@@ -436,6 +436,26 @@ func (dm *KubeArmorDaemon) ParseAndUpdateContainerSecurityPolicy(event tp.K8sKub
 		}
 	}
```
Comment (Aryan-sharma11) [inline KubeArmor/core/unorchestratedUpdates.go:435]: please add a comment specifying why are we doing this operation.

**Review by Aryan-sharma11 — COMMENTED** [review]
Thanks @haytok, I have tested it locally, and the changes are working as expected.  Just some small things to be addressed.

**Comment by haytok** [comment]
@Aryan-sharma11 

Thanks for review !!!

I was just about to reply. Respond to code reviews.

File: KubeArmor/core/unorchestratedUpdates.go (hunk 2 above)
Comment (haytok) [reply KubeArmor/core/unorchestratedUpdates.go:435]: What do you think of the comments below?

```
	// When the container name (value of kubearmor.io/container.name) specified in KubeArmorPolicy is changed, it is necessary to update the policies for the container with that name.
	for idx, endPoint := range dm.EndPoints {
		for policyIndex, policy := range endPoint.SecurityPolicies {
			if policy.Metadata["namespaceName"] == secPolicy.Metadata["namespaceName"] && policy.Metadata["policyName"] == secPolicy.Metadata["policyName"] && endPoint.EndPointName != containername {
```

File: KubeArmor/core/unorchestratedUpdates.go (hunk 1 above)
Comment (haytok) [reply KubeArmor/core/unorchestratedUpdates.go]: This is because if the `dm.Endpoints` object is deleted by the following process, the value of `i`, which indicates the index of the object, has changed.

```
dm.EndPoints = append(dm.EndPoints[:idx], dm.EndPoints[idx+1:]...)
```

https://github.com/kubearmor/KubeArmor/pull/1406/files#diff-168b945c99cdc3669f72461c0f4913020872a0e7ff4222676b356125676a4c64R443


If i is not recalculated, an out-of-array reference error will occur in the following operations.

```
dm.endpoints [i] = NewPoint
```

https://github.com/kubearmor/KubeArmor/pull/1406/files#diff-168b945c99cdc3669f72461c0f4913020872a0e7ff4222676b356125676a4c64R532

File: KubeArmor/core/unorchestratedUpdates.go (hunk 2 above)
Comment (Aryan-sharma11) [reply KubeArmor/core/unorchestratedUpdates.go:435]: how about 
``` 
// Updating container rules if there exists another container with same  `policy.Metadata["policyName"]` 
```

**Comment by haytok** [comment]
@Aryan-sharma11

Note that even in the `BPF-LSM` environment, this corrected code worked as expected. 

Development environment ([ref](https://haytok.github.io/post/20230919/))

```
OS Image: Amazon Linux 2023
Kernel Version: 6.1.49-70.116.amzn2023.x86_64
Initialized BPF-LSM Enforcer
Initialized Docker Handler (version: 1.41)
```

Apply blow policy

<details>
<summary> Policy </summary>

```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-block-policy
spec:
  severity: 3
  selector:
    matchLabels:
      kubearmor.io/container.name: foo
  process:
    matchPaths:
    - path: /usr/bin/apt
    - path: /usr/bin/apt-get
    # - path: /usr/bin/diff

      # apt update
      # apt-get update

  action:
    Block
```

</details>

Since apt update could not be performed on the container, it is thought that `BPF-LSM` is working properly.

```bash
[ec2-user@ip-172-31-42-22 ~]$ docker run --rm --name foo -it ubuntu bash
root@98bca4f7688b:/# apt update
bash: /usr/bin/apt: Permission denied
```

Apply updated below policy

<details>
<summary> Detail </summary>

```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-block-policy
spec:
  severity: 3
  selector:
    matchLabels:
      kubearmor.io/container.name: bar
  process:
    matchPaths:
    - path: /usr/bin/apt
    - path: /usr/bin/apt-get
    # - path: /usr/bin/diff

      # apt update
      # apt-get update

  action:
    Block
```

</details>

By changing the container name, it is now possible to execute `apt update`.

```
root@98bca4f7688b:/# apt update
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
...
```

File: KubeArmor/core/unorchestratedUpdates.go (hunk 1 above)
Comment (Aryan-sharma11) [reply KubeArmor/core/unorchestratedUpdates.go]: 🤔 That makes sense. So can we assign the value of i after [line 458](https://github.com/kubearmor/KubeArmor/pull/1406/files#diff-168b945c99cdc3669f72461c0f4913020872a0e7ff4222676b356125676a4c64R458)
and remove the loop from [here 431](https://github.com/kubearmor/KubeArmor/pull/1406/files#diff-168b945c99cdc3669f72461c0f4913020872a0e7ff4222676b356125676a4c64R431) 
this would also remove the need to reassign the value to `i` from [here 526 ]( https://github.com/kubearmor/KubeArmor/pull/1406/files#diff-168b945c99cdc3669f72461c0f4913020872a0e7ff4222676b356125676a4c64R526).

**Comment by haytok** [comment]
Hi, @Aryan-sharma11 

I've made refactorings based on the code review and fixes.
Could you please review when you have time ?

**Comment by Aryan-sharma11** [comment]
> Hi, @Aryan-sharma11
> 
> I've made refactorings based on the code review and fixes. Could you please review when you have time ?

@haytok  Can you please look at why the CI tests are failing? I think you might have to rebase, as we have made some changes in `Unorchestrated updates.go`  recently.

**Comment by haytok** [comment]
@Aryan-sharma11 

Thanks for comments !!!

> Can you please look at why the CI tests are failing? I think you might have to rebase, as we have made some changes in Unorchestrated updates.go recently.

As Aryan-sharma11 said, my development branch was behind the main branch, so it failed in CI. 

Therefore, I'll modify the code to match the main branch.

**Comment by haytok** [comment]
Hi, @Aryan-sharma11 (cc: @daemon1024)

The code was modified to pass tests that had previously failed. 

However, now, the test that has failed so far is as follows.

- https://github.com/kubearmor/KubeArmor/actions/runs/6263482069/job/17007982043?pr=1406

<details><summary> Details of ci-test-ginkgo / Auto-testing Framework / ubuntu-20.04 / containerd (pull_request) Failing </summary>
<p>

```bash
Summarizing 1 Failure:
  [FAIL] Ksp Apply Files Policies [It] it can audit accessing a file owner only from source path
  /home/runner/work/KubeArmor/KubeArmor/tests/ksp/ksp_test.go:886

Ran 37 of 37 Specs in 464.975 seconds
FAIL! -- 36 Passed | 1 Failed | 2 Flaked | 0 Pending | 0 Skipped
--- FAIL: TestKsp (464.98s)
FAIL

Ginkgo ran 6 suites in 10m30.445454346s

There were failures detected in the following suites:
  ksp ./ksp

Test Suite Failed
make: *** [Makefile:10: build] Error 1
Error: Process completed with exit code 2.
```

</p>
</details> 

The test applying the following manifest file has failed in [this CI job](https://github.com/kubearmor/KubeArmor/blob/main/.github/workflows/ci-test-ginkgo.yml#L86).

- [KubeArmor/tests/ksp/multiubuntu/ksp-group-2-audit-file-path-owner-from-source-path.yaml](https://github.com/kubearmor/KubeArmor/blob/main/tests/ksp/multiubuntu/ksp-group-2-audit-file-path-owner-from-source-path.yaml)

This test is in a normal mode other than `the systemd mode` that is subject to this change.

Therefore, it is generally assumed that this test will not fail.

I haven't know the root cause of failing because this commit isn't related to this test scenario, so could you get some advice?

File: KubeArmor/core/unorchestratedUpdates.go [hunk 3]
```diff
@@ -429,12 +429,59 @@ func (dm *KubeArmorDaemon) ParseAndUpdateContainerSecurityPolicy(event tp.K8sKub
...
+			if cfg.GlobalCfg.Policy {
+				// update security policies
+				dm.Logger.UpdateSecurityPolicies("MODIFIED", endPoint)
+
+				if dm.RuntimeEnforcer != nil && endPoint.PolicyEnabled == tp.KubeArmorPolicyEnabled {
+					// enforce security policies
+					dm.RuntimeEnforcer.UpdateSecurityPolicies(endPoint)
+				}
+			}
+		} else {
```
Comment (Aryan-sharma11) [inline KubeArmor/core/unorchestratedUpdates.go]: Imo, we don't need this else statement wdyt ?

**Review by Aryan-sharma11 — COMMENTED** [review]
@haytok Is there a specific reason to change the approach here as your earlier implementation was pretty straightforward imo? Also can you please attach the outputs?

**Comment by Aryan-sharma11** [comment]
> Hi, @Aryan-sharma11 (cc: @daemon1024)
> 
> The code was modified to pass tests that had previously failed.
> 
> However, now, the test that has failed so far is as follows.
> 
> * https://github.com/kubearmor/KubeArmor/actions/runs/6263482069/job/17007982043?pr=1406
> 
> Details of ci-test-ginkgo / Auto-testing Framework / ubuntu-20.04 / containerd (pull_request) Failing
> The test applying the following manifest file has failed in [this CI job](https://github.com/kubearmor/KubeArmor/blob/main/.github/workflows/ci-test-ginkgo.yml#L86).
> 
> * [KubeArmor/tests/ksp/multiubuntu/ksp-group-2-audit-file-path-owner-from-source-path.yaml](https://github.com/kubearmor/KubeArmor/blob/main/tests/ksp/multiubuntu/ksp-group-2-audit-file-path-owner-from-source-path.yaml)
> 
> This test is in a normal mode other than `the systemd mode` that is subject to this change.
> 
> Therefore, it is generally assumed that this test will not fail.
> 
> I haven't know the root cause of failing because this commit isn't related to this test scenario, so could you get some advice?

Yes, we are having some issues with containerd tests, we are working on it.

File: KubeArmor/core/unorchestratedUpdates.go [hunk 4]
```diff
@@ -429,12 +429,59 @@ func (dm *KubeArmorDaemon) ParseAndUpdateContainerSecurityPolicy(event tp.K8sKub
...
+		if kl.MatchIdentities(secPolicy.Spec.Selector.Identities, endPoint.Identities) && i < 0 {
 			i = idx
 			newPoint = endPoint
-			break
+		}
+
+		for policyIndex, policy := range endPoint.SecurityPolicies {
+			if policy.Metadata["namespaceName"] == secPolicy.Metadata["namespaceName"] && policy.Metadata["policyName"] == secPolicy.Metadata["policyName"] && endPoint.EndPointName != containername {
+				renamedContainerIndex = idx
+				deletedPolicyIndex = policyIndex
```
Comment (daemon1024) [inline KubeArmor/core/unorchestratedUpdates.go]: Today KubeArmor only supports, single container policies. But in future there will be Policy Matching to suppport policies on multiple containers. This logic will not scale when we add that. We should implement this in such a way, that it's not a special case handling but handle it in a natural way so as to address the issue. WDYT?

**Comment by haytok** [comment]
@Aryan-sharma11 

> Yes, we are having some issues with containerd tests, we are working on it.

OK, thank you !!!

> Is there a specific reason to change the approach here as your earlier implementation was pretty straightforward imo? Also can you please attach the outputs?

After the code review from daemon1024 has been completed, the results of the operation confirmation will be shared.

**Comment by haytok** [comment]
Hi, @Aryan-sharma11 and @daemon1024 



The parts of the review have been fixed, so please review again.

to @Aryan-sharma11

> Is there a specific reason to change the approach here as your earlier implementation was pretty straightforward imo? 



I have refactored based on the review below.

- https://github.com/kubearmor/KubeArmor/pull/1406#discussion_r1331465269



Additionally, this implementation includes the following points.

- Fixed so that when applying a policy with a changed container name, security enforcement are not enforced on the old container
  - If one or more policies have been applied to one container and the container name in a policy is changed, it has been fixed so that security enforcement are not applied to the container to which that policy was previously applied (ref: Below `Test Case 1` and `Test Case 2`)
- Also, fixed so that `dm.Endpoints` is updated by applying a policy where the container name was changed

> Also can you please attach the outputs?



Below are the tests that confirmed that the fix worked in the pull request and their results.

<details><summary> Test case 1 </summary>
<p>

Create a below test script (`/home/ubuntu/scenario_1.sh`)

```bash
ubuntu ~
> cat scenario_1.sh
echo "Start Scenario 1";

POLICY_NAME="block_apt.yaml"
BACKUP_POLICY_NAME="block-apt.yaml"
CONTAINER_NAME="test"
APPARMOR_PROFILE="kubearmor_foo"

cat <<EOF > $POLICY_NAME
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-apt
spec:
  severity: 3
  selector:
    matchLabels:
      kubearmor.io/container.name: foo
  process:
    matchPaths:
    - path: /usr/bin/apt
    - path: /usr/bin/apt-get
  action:
    Block
EOF

echo "-+-+-+-+-+-+-+-+-+-+";
echo "Add $POLICY_NAME";
karmor vm policy add $POLICY_NAME
sleep 1

echo "-+-+-+-+-+-+-+-+-+-+";
echo "Run container";
docker run -itd --security-opt apparmor=$APPARMOR_PROFILE --name $CONTAINER_NAME ubuntu bash

echo "-+-+-+-+-+-+-+-+-+-+";
echo "Run apt update";
docker exec -it $CONTAINER_NAME bin/bash -c "/usr/bin/apt update" # Permission denied

echo "-+-+-+-+-+-+-+-+-+-+";
echo "Run apt-get update";
docker exec -it $CONTAINER_NAME bin/bash -c "/usr/bin/apt-get update" # Permission denied

echo "-+-+-+-+-+-+-+-+-+-+";
echo "Update the container name from foo to bar.";

sed -i 's/foo/bar/g' $POLICY_NAME

karmor vm policy add $POLICY_NAME
sleep 1

echo "-+-+-+-+-+-+-+-+-+-+";
echo "Run apt update";
docker exec -it $CONTAINER_NAME bin/bash -c "/usr/bin/apt update"

echo "-+-+-+-+-+-+-+-+-+-+";
echo "Run apt-get update";
docker exec -it $CONTAINER_NAME bin/bash -c "/usr/bin/apt-get update"

echo "-+-+-+-+-+-+-+-+-+-+";
docker stop $CONTAINER_NAME
docker rm $CONTAINER_NAME
sudo rm /opt/kubearmor/policies/$BACKUP_POLICY_NAME
cd ~/KubeArmor/KubeArmor
./deploy.sh
cd -
```

Run this script

```bash
ubuntu ~
> bash scenario_1.sh
Start Scenario 1
-+-+-+-+-+-+-+-+-+-+
Add block_apt.yaml
Success
-+-+-+-+-+-+-+-+-+-+
Run container
8c79aff73b6c231c36ad7548513cf66250c0bf99844861c03e4ed9caee96ed07
-+-+-+-+-+-+-+-+-+-+
Run apt update
bin/bash: line 1: /usr/bin/apt: Permission denied
-+-+-+-+-+-+-+-+-+-+
Run apt-get update
bin/bash: line 1: /usr/bin/apt-get: Permission denied
-+-+-+-+-+-+-+-+-+-+
Update the container name from foo to bar.
Success
-+-+-+-+-+-+-+-+-+-+
Run apt update
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]
Get:3 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [1016 kB]
Get:4 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [44.0 kB]
Get:5 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [998 kB]
Get:6 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [1144 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]
Get:11 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [1165 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1287 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1264 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [49.9 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [28.1 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [50.4 kB]
Fetched 27.3 MB in 7s (4152 kB/s)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
4 packages can be upgraded. Run 'apt list --upgradable' to see them.
-+-+-+-+-+-+-+-+-+-+
Run apt-get update
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists... Done
-+-+-+-+-+-+-+-+-+-+
test
test
sudo systemctl disable kubearmor
systemctl start kubearmor
/home/ubuntu
```

Check journal log

```bash
Sep 30 21:01:08 ip-172-31-33-167 kubearmor[777272]: 2023-09-30 21:01:08.702415        INFO        Detected a Container Security Policy (added/container_namespace/block-apt)
Sep 30 21:01:08 ip-172-31-33-167 kubearmor[777272]: 2023-09-30 21:01:08.726177        INFO        Registered the AppArmor profile (kubearmor_foo)
Sep 30 21:01:08 ip-172-31-33-167 kubearmor[777272]: 2023-09-30 21:01:08.751809        INFO        Updated 2 security rule(s) to container_namespace/foo/kubearmor_foo
Sep 30 21:01:08 ip-172-31-33-167 kubearmor[777272]: i: 0, EndPointName: foo, number of policies: 1
Sep 30 21:01:10 ip-172-31-33-167 kubearmor[777272]: 2023-09-30 21:01:10.137178        INFO        Successfully added visibility map with key={PidNS:4026532233 MntNS:4026532230} to the kernel
Sep 30 21:01:10 ip-172-31-33-167 kubearmor[777272]: 2023-09-30 21:01:10.137208        INFO        Detected a container (added/8c79aff73b6c)
Sep 30 21:01:10 ip-172-31-33-167 kubearmor[777272]: 2023-09-30 21:01:10.343101        INFO        Detected a Container Security Policy (added/container_namespace/block-apt)
Sep 30 21:01:10 ip-172-31-33-167 kubearmor[777272]: 2023-09-30 21:01:10.369384        INFO        Updated 0 security rule(s) to container_namespace/foo/kubearmor_foo
Sep 30 21:01:10 ip-172-31-33-167 kubearmor[777272]: 2023-09-30 21:01:10.392903        INFO        Registered the AppArmor profile (kubearmor_bar)
Sep 30 21:01:10 ip-172-31-33-167 kubearmor[777272]: 2023-09-30 21:01:10.419052        INFO        Updated 2 security rule(s) to container_namespace/bar/kubearmor_bar
Sep 30 21:01:10 ip-172-31-33-167 kubearmor[777272]: i: 0, EndPointName: bar, number of policies: 1
Sep 30 21:01:31 ip-172-31-33-167 kubearmor[777272]: 2023-09-30 21:01:31.217171        INFO        Successfully deleted visibility map with key={PidNS:4026532233 MntNS:4026532230} from the kernel
Sep 30 21:01:31 ip-172-31-33-167 kubearmor[777272]: 2023-09-30 21:01:31.217213        INFO        Detected a container (removed/8c79aff73b6c)
```

</p>
</details> 

<details><summary> Test case 2 </summary>
<p>

Create a below test script (`/home/ubuntu/scenario_2.sh`)

```bash
ubuntu ~
> cat scenario_2.sh
echo "Start Scenario 2";

POLICY_FOR_DIFF="block_diff.yaml"
BACKUP_POLICY_FOR_DIFF="block-diff.yaml"
POLICY_FOR_LS="block_ls.yaml"
BACKUP_POLICY_FOR_LS="block-ls.yaml"
POLICY_FOR_SLEEP="block_sleep.yaml"
BACKUP_POLICY_FOR_SLEEP="block-sleep.yaml"
CONTAINER_NAME="test"
APPARMOR_PROFILE="kubearmor_foo"

cat <<EOF > $POLICY_FOR_DIFF
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-diff
spec:
  severity: 3
  selector:
    matchLabels:
      kubearmor.io/container.name: foo
  process:
    matchPaths:
    - path: /usr/bin/diff
    - path: /usr/bin/cd
  action:
    Block
EOF

cat <<EOF > $POLICY_FOR_LS
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-ls
spec:
  selector:
    matchLabels:
      # policyName
      kubearmor.io/container.name: foo
  process:
    matchPaths:
      - path: /usr/bin/ls
  action:
    Block
EOF

cat <<EOF > $POLICY_FOR_SLEEP
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: block-sleep
spec:
  selector:
    matchLabels:
      kubearmor.io/container.name: foo
  process:
    matchPaths:
      - path: /usr/bin/sleep
  action:
    Block
EOF

echo "-+-+-+-+-+-+-+-+-+-+";
echo "Add $POLICY_FOR_DIFF";
karmor vm policy add $POLICY_FOR_DIFF
sleep 1

echo "Add $POLICY_FOR_LS";
karmor vm policy add $POLICY_FOR_LS
sleep 1

echo "-+-+-+-+-+-+-+-+-+-+";
echo "Run container";
docker run -itd --security-opt apparmor=$APPARMOR_PROFILE --name $CONTAINER_NAME ubuntu bash

echo "-+-+-+-+-+-+-+-+-+-+";
echo "Run diff";
docker exec -it $CONTAINER_NAME bin/bash -c "/usr/bin/diff" # Permission denied

echo "Run ls";
docker exec -it $CONTAINER_NAME bin/bash -c "/usr/bin/ls" # Permission denied

echo "-+-+-+-+-+-+-+-+-+-+";
echo "Update the container name of $POLICY_FOR_DIFF from foo to bar.";
sed -i 's/foo/bar/g' $POLICY_FOR_DIFF

karmor vm policy add $POLICY_FOR_DIFF
sleep 1

echo "Run diff";
docker exec -it $CONTAINER_NAME bin/bash -c "/usr/bin/diff"

echo "-+-+-+-+-+-+-+-+-+-+";
echo "Update the container name of $POLICY_FOR_LS from foo to bar.";
sed -i 's/foo/bar/g' $POLICY_FOR_LS

karmor vm policy add $POLICY_FOR_LS
sleep 1

echo "Run ls";
docker exec -it $CONTAINER_NAME bin/bash -c "/usr/bin/ls"

echo "-+-+-+-+-+-+-+-+-+-+";
echo "Add $POLICY_FOR_SLEEP";
karmor vm policy add $POLICY_FOR_SLEEP
sleep 1

echo "Run sleep";
docker exec -it $CONTAINER_NAME bin/bash -c "/usr/bin/sleep 1" # Permission denied

echo "-+-+-+-+-+-+-+-+-+-+";
echo "Update the container name of $POLICY_FOR_SLEEP from foo to bar.";
sed -i 's/foo/bar/g' $POLICY_FOR_SLEEP

karmor vm policy add $POLICY_FOR_SLEEP
sleep 1

echo "Run sleep";
docker exec -it $CONTAINER_NAME bin/bash -c "/usr/bin/sleep 1"

echo "-+-+-+-+-+-+-+-+-+-+";
docker stop $CONTAINER_NAME
docker rm $CONTAINER_NAME
sudo rm /opt/kubearmor/policies/$BACKUP_POLICY_FOR_DIFF
sudo rm /opt/kubearmor/policies/$BACKUP_POLICY_FOR_LS
sudo rm /opt/kubearmor/policies/$BACKUP_POLICY_FOR_SLEEP
cd ~/KubeArmor/KubeArmor
./deploy.sh
cd -
```

Run this script

```bash
ubuntu ~
> bash scenario_2.sh
Start Scenario 2
-+-+-+-+-+-+-+-+-+-+
Add block_diff.yaml
Success
Add block_ls.yaml
Success
-+-+-+-+-+-+-+-+-+-+
Run container
0f33961946ec93d2d9b82621a800ab97c57c0a2056626006007046e9345b085a
-+-+-+-+-+-+-+-+-+-+
Run diff
bin/bash: line 1: /usr/bin/diff: Permission denied
Run ls
bin/bash: line 1: /usr/bin/ls: Permission denied
-+-+-+-+-+-+-+-+-+-+
Update the container name of block_diff.yaml from foo to bar.
Success
Run diff
/usr/bin/diff: missing operand after '/usr/bin/diff'
/usr/bin/diff: Try '/usr/bin/diff --help' for more information.
-+-+-+-+-+-+-+-+-+-+
Update the container name of block_ls.yaml from foo to bar.
Success
Run ls
bin  boot  dev	etc  home  lib	lib32  lib64  libx32  media  mnt  opt  proc  root  run	sbin  srv  sys	tmp  usr  var
-+-+-+-+-+-+-+-+-+-+
Add block_sleep.yaml
Success
Run sleep
bin/bash: line 1: /usr/bin/sleep: Permission denied
-+-+-+-+-+-+-+-+-+-+
Update the container name of block_sleep.yaml from foo to bar.
Success
Run sleep
-+-+-+-+-+-+-+-+-+-+
test
test
sudo systemctl disable kubearmor
systemctl start kubearmor
/home/ubuntu
```

Check journal log

```bash
Sep 30 20:57:00 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:00.569467        INFO        Detected a Container Security Policy (added/container_namespace/block-diff)
Sep 30 20:57:00 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:00.594251        INFO        Registered the AppArmor profile (kubearmor_foo)
Sep 30 20:57:00 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:00.621110        INFO        Updated 2 security rule(s) to container_namespace/foo/kubearmor_foo
Sep 30 20:57:00 ip-172-31-33-167 kubearmor[776813]: i: 0, EndPointName: foo, number of policies: 1
Sep 30 20:57:01 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:01.665892        INFO        Detected a Container Security Policy (added/container_namespace/block-ls)
Sep 30 20:57:01 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:01.691781        INFO        Updated 3 security rule(s) to container_namespace/foo/kubearmor_foo
Sep 30 20:57:01 ip-172-31-33-167 kubearmor[776813]: i: 0, EndPointName: foo, number of policies: 2
Sep 30 20:57:03 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:03.339244        INFO        Detected a Container Security Policy (added/container_namespace/block-diff)
Sep 30 20:57:03 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:03.365023        INFO        Updated 1 security rule(s) to container_namespace/foo/kubearmor_foo
Sep 30 20:57:03 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:03.389353        INFO        Registered the AppArmor profile (kubearmor_bar)
Sep 30 20:57:03 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:03.414962        INFO        Updated 2 security rule(s) to container_namespace/bar/kubearmor_bar
Sep 30 20:57:03 ip-172-31-33-167 kubearmor[776813]: i: 0, EndPointName: foo, number of policies: 1
Sep 30 20:57:03 ip-172-31-33-167 kubearmor[776813]: i: 1, EndPointName: bar, number of policies: 1
Sep 30 20:57:03 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:03.485161        INFO        Successfully added visibility map with key={PidNS:4026532233 MntNS:4026532230} to the kernel
Sep 30 20:57:03 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:03.485189        INFO        Detected a container (added/0f33961946ec/pidns=4026532233/mntns=4026532230)
Sep 30 20:57:04 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:04.575856        INFO        Detected a Container Security Policy (added/container_namespace/block-ls)
Sep 30 20:57:04 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:04.601975        INFO        Updated 0 security rule(s) to container_namespace/foo/kubearmor_foo
Sep 30 20:57:04 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:04.627628        INFO        Updated 3 security rule(s) to container_namespace/bar/kubearmor_bar
Sep 30 20:57:04 ip-172-31-33-167 kubearmor[776813]: i: 0, EndPointName: bar, number of policies: 2
Sep 30 20:57:05 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:05.780950        INFO        Detected a Container Security Policy (added/container_namespace/block-sleep)
Sep 30 20:57:05 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:05.807897        INFO        Updated 1 security rule(s) to container_namespace/foo/kubearmor_foo
Sep 30 20:57:05 ip-172-31-33-167 kubearmor[776813]: i: 0, EndPointName: bar, number of policies: 2
Sep 30 20:57:05 ip-172-31-33-167 kubearmor[776813]: i: 1, EndPointName: foo, number of policies: 1
Sep 30 20:57:06 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:06.958159        INFO        Detected a Container Security Policy (added/container_namespace/block-sleep)
Sep 30 20:57:06 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:06.984674        INFO        Updated 0 security rule(s) to container_namespace/foo/kubearmor_foo
Sep 30 20:57:07 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:07.011308        INFO        Updated 4 security rule(s) to container_namespace/bar/kubearmor_bar
Sep 30 20:57:07 ip-172-31-33-167 kubearmor[776813]: i: 0, EndPointName: bar, number of policies: 3
Sep 30 20:57:19 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:19.553189        INFO        Successfully deleted visibility map with key={PidNS:4026532233 MntNS:4026532230} from the kernel
Sep 30 20:57:19 ip-172-31-33-167 kubearmor[776813]: 2023-09-30 20:57:19.553229        INFO        Detected a container (removed/0f33961946ec/pidns=4026532233/mntns=4026532230)
```

</p>
</details> 

Note that I confirmed that the bug has been fixed by writing a debug program to check `dm.Endpoints` in the following part of [parseAndUpdateContainerSecurityPolicy()](https://github.com/kubearmor/KubeArmor/blob/main/KubeArmor/core/unorchestratedUpdates.go#L83C1-L555). 



- https://github.com/kubearmor/KubeArmor/blob/main/KubeArmor/core/unorchestratedUpdates.go#L547

<details>
<summary> Debug code </summary>

```golang
       for i, endPoint := range dm.EndPoints {
               fmt.Printf("i: %d, EndPointName: %s, number of policies: %d\n", i, endPoint.EndPointName, len(endPoint.SecurityPolicies))
       }
```

</details>



From the above, it can be confirmed that when a Policy with a changed container name is applied, it will not be restricted by the Policy other than the target container. Also, I think you can confirm from the journal log that `dm.Endpoints` has also been successfully updated.

to @daemon1024



I've refactored the implementation below for scalability when it becomes possible to specify multiple containers in a single Policy in the future.

```golang
				renamedContainerIndex = idx
				deletedPolicyIndex = policyIndex
```

File: KubeArmor/core/unorchestratedUpdates.go [hunk 5]
```diff
@@ -426,15 +426,70 @@ func (dm *KubeArmorDaemon) ParseAndUpdateContainerSecurityPolicy(event tp.K8sKub
...
+			newPoint = endPoint
+		}
+
+		for policyIndex, policy := range endPoint.SecurityPolicies {
+			if policy.Metadata["namespaceName"] == secPolicy.Metadata["namespaceName"] && policy.Metadata["policyName"] == secPolicy.Metadata["policyName"] && endPoint.EndPointName != containername {
+				renamedContainer := tp.RenamedContainer{
+					EndPointName:       endPoint.EndPointName,
+					DeletedPolicyIndex: policyIndex,
+				}
+				renamedContainers = append(renamedContainers, renamedContainer)
```
Comment (daemon1024) [inline KubeArmor/core/unorchestratedUpdates.go]: Any particular reason to store it in an array and loop over it again? Why not just call the deletion code here itself?

**Comment by haytok** [comment]
@daemon1024 @Aryan-sharma11 

I've updated based on the review, could you please check it?

Note that this change confirms the expected behavior from `Test Case 1` and `Test Case 2` described above.

**Review by daemon1024 — APPROVED** [review]

File: KubeArmor/core/unorchestratedUpdates.go [hunk 6]
```diff
@@ -426,15 +426,50 @@ func (dm *KubeArmorDaemon) ParseAndUpdateContainerSecurityPolicy(event tp.K8sKub
...
-	newPoint := tp.EndPoint{}
-
 	i := -1
+	endPointIndex := -1
+	newPoint := tp.EndPoint{}
 
 	for idx, endPoint := range dm.EndPoints {
-		if kl.MatchIdentities(secPolicy.Spec.Selector.Identities, endPoint.Identities) {
-			i = idx
+		endPointIndex += 1
```
Comment (Aryan-sharma11) [inline KubeArmor/core/unorchestratedUpdates.go]: please handle this lint warning

**Review by Aryan-sharma11 — APPROVED** [review]

**Comment by haytok** [comment]
Hi, @Aryan-sharma11 @daemon1024 

The go-lint warning was fixed, and the commit was squashed and pushed.
Could you please check ?

**Comment by Aryan-sharma11** [comment]
LGTM! Thanks for the PR @haytok
