### PR TITLE
bpf,enforcer: remove conditional compilation and add alternate bpflsm availability check

### LINKED ISSUE #756: Minikube Start is failing with latest version of minikube (1.26) and k8s(1.24)
## Minikube start

**General Information**

- Environment (minikube)
- Kernel version (Linux eswar-LEGION 5.13.0-52-generic #59~20.04.1-Ubuntu SMP Thu Jun 16 21:21:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux)

**To Reproduce**

1. Goto contributions minikube.
2. Install minikube and virtualbox using scripts mentioned under contributions/minikube dir.
3. Then run minikube with start_minikube.sh script. 

**Observed behavior**
Minikube throws an error and fails to start.
minikube-err

**Expected behavior**
Minikube is expected to start with no issues/errors. 

**Temporary solution**
with minikube start, use the below flag
`--kubernetes-version=1.23.1`

### PR DESCRIPTION
**Pull request by daemon1024**
**Purpose of PR?**:
We now compile everything and let probes loading fail at runtime, the failed probes don't impact functioning of other probes so the added complexity to conditional compile wasn't needed.

Remove dependency for /sys/kernel/security/lsm to check for BPF LSM. This should help things work for Minikube and KIND. Yet to be tested on KIND.

Hopefully closes #756 #903
Ref #928

**Does this PR introduce a breaking change?**
Yes, New KubeArmor init container won't work with older KubeArmor images

**If the changes in this PR are manually verified, list down the scenarios covered:**:
Test in Minikube with KVM2 driver uses custom buildroot iso with BPFLSM support but no CONFIG_SECURITY_PATH

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_
We should enforce stable init container before proceeding with this

Need to update docs once Minikube and KIND support verified.

**Checklist:**
- [x] Bug fix.
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`

### CODE REVIEW

File: KubeArmor/enforcer/runtimeEnforcer.go [hunk 1]
```diff
@@ -125,31 +127,44 @@ func NewRuntimeEnforcer(node tp.Node, logger *fd.Feeder) *RuntimeEnforcer {
...
+
+probeBPFLSM:
+	if !kl.ContainsElement(lsms, "bpf") {
+		err := features.HaveProgramType(ebpf.LSM)
+		if err == nil {
+			lsms = append(lsms, "bpf")
+		} else {
+			re.Logger.Warnf("BPF LSM not supported %s", err.Error())
 		}
 	}
```
Comment (Ankurk99) [inline KubeArmor/enforcer/runtimeEnforcer.go]: > Remove dependency for /sys/kernel/security/lsm to check for BPF LSM. This should help things work for Minikube and KIND. Yet to be tested on KIND.
 
I didn't understand this. Here we are checking if "bpf" string is found in /sys/kernel/security/lsm and in case of minikube this file doesn't exist. How will this work in minikube?

Comment (daemon1024) [reply KubeArmor/enforcer/runtimeEnforcer.go]: It's a not (`<!>kl.Contains`) check. We skip the following check if we already found bpf in the said file. We should only check for support using this method iff we didn't find the lsm file or the lsm file didn't have bpf.

Does that make sense?

**Comment by rksharma95** [comment]
i think the tests are failing due to test utility function not able to find pods where it's looking for pods
with `apparmor` specific annotations `container.apparmor.security.beta.kubernetes.io/...`. that will be patched to the endpoints in case if enforcer is `apparmor`.

and with current change where we have removed the dependency for `/sys/kernel/security/lsm` to check for `BPF LSM`, and in the lsm-order `bpf` is having higher priority the enforcer used by the `KubeArmor` in test env will be `bpf`.

and it's obvious for the pods to not have `apparmor` specific annotations. i think we need to refactor tests.

**Comment by daemon1024** [comment]
Ohh makes sense. Does that mean bpflsm is supported on Github Runners? Or the code is not apt 😢 

I will just confirm if Github Runners do support BPF LSM. If yes then will just force tests to use apparmor else will need to debug PR.

**Comment by daemon1024** [comment]
There's some discrepancy in the support check. Will have to defer this for later since needs further investigation.

File: KubeArmor/utils/bpflsmprobe/probe.go [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+	record, err := rd.Read()
+	if err != nil {
+		return err
+	}
+
+	if err := binary.Read(bytes.NewBuffer(record.RawSample), binary.LittleEndian, &event); err != nil {
+		return err
+	}
+
+	return nil
```
Comment (nyrahul) [inline KubeArmor/utils/bpflsmprobe/probe.go]:
```suggestion
	return binary.Read(bytes.NewBuffer(record.RawSample), binary.LittleEndian, &event)
```

File: KubeArmor/utils/bpflsmprobe/probe.go [hunk 3]
```diff
@@ -0,0 +1,68 @@
+// SPDX-License-Identifier: Apache-2.0
+// Copyright 2023 Authors of KubeArmor
+
+package probe
```
Comment (nyrahul) [inline KubeArmor/utils/bpflsmprobe/probe.go:5]:
```suggestion
// probe to check whether the probed LSM support is available.
package probe
```

**Review by nyrahul — CHANGES_REQUESTED** [review]
Two minor comments. Otherwise LGTM 👍

**Review by nyrahul — APPROVED** [review]
LGTM 👍
