### PR TITLE
Bpftool fix

### LINKED ISSUE #1400: Build bpftool from source in Vagrant env
`bpftool` can through out the following error

```
Error: failed to load BTF from /sys/kernel/btf/vmlinux: Unknown error -4001
```

in some cases due to kernel version mismatch with bpftool package installation causing issues in dev env. 

The workaround is to build bpftool from source in the env. We should automate this in the vagrantfile to reduce hiccups for contributors or dev env setup.

Ref:
https://stackoverflow.com/questions/70093863/linux-btf-bpftool-failed-to-get-ehdr-from-sys-kernel-btf-vmlinux
https://github.com/libbpf/bpftool#build

### PR DESCRIPTION
**Pull request by pavan12395**
**Purpose of PR?**:

Fixes #

**Does this PR introduce a breaking change?**
No

**If the changes in this PR are manually verified, list down the scenarios covered:**:
Works for NETNEXT=0,1 and OS=ubuntu

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [ ] Bug fix. Fixes #1400 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Review by kranurag7 — CHANGES_REQUESTED** [review]
Hey @pavan12395 Thanks for the PR. Can we use `$(uname -r)` instead of hardcoding the values? Also, please check if only `linux-tools-generic` works. IMHO, I think we also require `linux-tools-$(uname -r)` 

I checked this on an Ubuntu instance.

File: contribution/vagrant/Vagrantfile [hunk 1]
```diff
@@ -109,6 +112,14 @@ Vagrant.configure("2") do |config|
...
 
   else # ubuntu
+    if NETNEXT == "0" or NETNEXT == "-1" then
+        # Updating kernel image to 5.15 required for building latest version of bpftool.
+        config.vm.provision :shell, :inline => "sudo apt-get update -y"
+        config.vm.provision :shell, :inline => "sudo apt-get install linux-image-5.15.0-73-generic linux-headers-5.15.0-73-generic linux-tools-generic -y"
+        config.vm.provision :shell, :inline => "sudo sed -i 's/^GRUB_DEFAULT=.*/GRUB_DEFAULT=\"Advanced options for Ubuntu>Ubuntu, with Linux 5.15.0-73.80~20.04.1 \"/' /etc/default/grub"
+        config.vm.provision :shell, :inline => "sudo update-grub"
+        config.vm.provision :reload
+    end
```
Comment (daemon1024) [inline contribution/vagrant/Vagrantfile]: We shouldn't do this

File: contribution/self-managed-k8s/setup.sh [hunk 2]
```diff
@@ -120,3 +120,16 @@ sudo mv kustomize /usr/local/bin
...
+
+cd $HOME
+git clone --recurse-submodules https://github.com/libbpf/bpftool.git
+cd bpftool
+git submodule update --init
+cd src
+sudo apt-get install make -y
+sudo apt install pkgconf -y
+sudo apt install build-essential -y
+sudo make install
```
Comment (daemon1024) [inline contribution/self-managed-k8s/setup.sh]: As per my undertsanding, bpftool has statically compiled releases now. It should be fine to just install latest bpftool here?

You can reference this for installing bpftool
https://github.com/kubearmor/KubeArmor/blob/3bf31234d0927bdb5d5799e6b021d5dba4690de0/Dockerfile.init#L27-L29

**Review by daemon1024 — CHANGES_REQUESTED** [review]
Thanks a lot for the quick PR. Please find comments inline.

File: contribution/self-managed-k8s/setup.sh (hunk 2 above)
Comment (kranurag7) [reply contribution/self-managed-k8s/setup.sh]: I forgot this point of fetching from GitHub releases. I think the binaries will still dynamically linked but should work. Thanks for pointing this out.

Comment (daemon1024) [reply contribution/self-managed-k8s/setup.sh]: @kranurag7 https://github.com/libbpf/bpftool/releases/tag/v7.2.0 if you check the CI release notes, it does mention statically linked binaries.

I verified them manually
image

Comment (kranurag7) [reply contribution/self-managed-k8s/setup.sh]: Thanks Barun, I thought compiling this would reference LDPATH at least somewhere but as you verified that's not the case. In retrospect, I should have verified it once. :(

Comment (daemon1024) [reply contribution/self-managed-k8s/setup.sh]: No worries 😁

File: contribution/vagrant/Vagrantfile (hunk 1 above)
Comment (pavan12395) [reply contribution/vagrant/Vagrantfile]: Thanks a lot for the quick and clear review @daemon1024 , Repo said linux-genric-tools >=1.15 is required for building bpftool , However works fine for the static binaries of ubuntu 18,20,22

File: contribution/self-managed-k8s/setup.sh (hunk 2 above)
Comment (pavan12395) [reply contribution/self-managed-k8s/setup.sh]: Changed sources to static binaries , Working fine for NETNEXT=-1,0,1

File: contribution/vagrant/Vagrantfile [hunk 3]
```diff
@@ -83,6 +83,9 @@ Vagrant.configure("2") do |config|
       # skip to set up the development env
     else
       # install base dependencies
+
```
Comment (daemon1024) [inline contribution/vagrant/Vagrantfile]: Small nit, let's not add unnecessary new lines. Rest LGTM. Thanks for the updates.

**Review by daemon1024 — CHANGES_REQUESTED** [review]

**Comment by daemon1024** [comment]
Can you please squash your commits as well?

File: contribution/vagrant/Vagrantfile (hunk 3 above)
Comment (pavan12395) [reply contribution/vagrant/Vagrantfile]: Deleted Empty lines , Done.

**Comment by pavan12395** [comment]
> Can you please squash your commits as well?

D

**Comment by pavan12395** [comment]
> Can you please squash your commits as well?

Done

**Review by daemon1024 — APPROVED** [review]

File: contribution/self-managed-k8s/setup.sh [hunk 4]
```diff
@@ -120,3 +120,20 @@ sudo mv kustomize /usr/local/bin
...
+cd $HOME
+export arch=$(uname -m)
+export bpftool_version=v7.2.0
+if [[ "$arch" == "aarch64" ]]; then
+  arch=arm64;
+elif [[ "$arch" == "x86_64" ]]; then
+  arch=amd64;
+fi
+curl -LO https://github.com/libbpf/bpftool/releases/download/$bpftool_version/bpftool-$bpftool_version-$arch.tar.gz && \
+    tar -xzf bpftool-$bpftool_version-$arch.tar.gz -C /usr/local/bin && \
```
Comment (kranurag7) [inline contribution/self-managed-k8s/setup.sh]:
```suggestion
    sudo tar -xzf bpftool-$bpftool_version-$arch.tar.gz -C /usr/local/bin && \
```

**Review by kranurag7 — CHANGES_REQUESTED** [review]
We will require `sudo` to extract files in `/usr/local/bin` directory otherwise we will get permission errors. 
```bash
tar -xzf bpftool-v7.2.0-amd64.tar.gz -C /usr/local/bin/
tar: bpftool: Cannot open: Permission denied
tar: Exiting with failure status due to previous errors
```

**Comment by pavan12395** [comment]
`tar -xzf bpftool-$bpftool_version-$arch.tar.gz -C /usr/local/bin && \
    sudo chmod +x /usr/local/bin/bpftool
`
Didnt give any issues for me , as I was changing the permissions after I extracted them to /usr/local/bin

**Comment by daemon1024** [comment]
script might have sudo privileges, but it's fine to include it.

**Review by kranurag7 — APPROVED** [review]
I was testing the script part standalone and got the error mentioned above. 

LGTM 👍🏻, Thanks for the contribution @pavan12395

**Review by daemon1024 — APPROVED** [review]
