### PR TITLE
Fixes #769 Ignore empty policy in Kubeamor

### LINKED ISSUE #769: Ignore empty policy
## Bug Report

**Environment**
KubeArmor running in host	mode

**General Information**
Add check to KubeArmor to ignore accepting blank policies. If a policy ends with "---" KubeArmor currently takes it as an additional empty policy.
It will have issues for eg: If we run KubeArmor in containerized mode then it will create an empty apparmor profile (with name kubearmor_) for that empty policy.

**Expected behavior**
KubeArmor should ignore blank policies (policy yaml ending with "---").

### PR DESCRIPTION
**Pull request by Chinwendu20**
~~I wrote a check for host policy and container policy. I placed them in the kubeamor/common/common.go file and imported them in the kubeamor/policy/policy.go file. If the policy file is empty, res.status is assigned 0, container policy is not updated and then there would be a warning log with message, "Empty policy Event" . The function~~

Does not apply anymore

Fixes #769

### CODE REVIEW

**Comment by rksharma95** [comment]
@Chinwendu20 appreciate your contribution, Check the DCO failed, Please use git commit -s to sign-off in your commits. Thanks.

**Comment by Chinwendu20** [comment]
Okay looks like my package import path was incorrect. I would fix that

File: KubeArmor/common/common.go [hunk 1]
```diff
@@ -443,3 +444,100 @@ func WriteToFile(val interface{}, destFile string) error {
...
+			}
+		case reflect.Ptr:
+
+			if !struct_value.IsNil(){	
+
+				EmptyPolicy=false
+			
+			}
+		}
+	}
```
Comment (daemon1024) [inline KubeArmor/common/common.go]: Why do we need to use the reflect package here?

Shouldn't the check be as simple as 
`if policyEvent.Object.Metadata &&  policyEvent.Object.Metadata.Name != "" {}`

**Review by daemon1024 — CHANGES_REQUESTED** [review]
Hey @Chinwendu20, Thanks a lot for handling the changes!

As I iterated on Slack,
We should check for 
policyEvent.Object.Name != ""

And that should be good enough.

File: KubeArmor/common/common.go (hunk 1 above)
Comment (Chinwendu20) [reply KubeArmor/common/common.go]: Okay I saw that the Name field in Metadata is optional. Actually there is another field Generate_Name that one can use to generate metadata name. So a valid policy can do without that.

image

Comment (Chinwendu20) [reply KubeArmor/common/common.go]: Thanks. You are right even if that were to be the case, then I should check for only Name and GenerateName field. Just when I looked at it I saw that all the fields were optional and perhaps it needed just one field.

Comment (daemon1024) [reply KubeArmor/common/common.go]: > Is required when creating resources, some resources **may allow** a client to request the generation of an appropriate  automatically.

As it mentions may request client for auto generation, KubeArmor doesn't do that, so Ig we can deem it as required.

**Comment by daemon1024** [comment]
I couldn't find it but can we check the apiVersion and Kind on KubeArmor side as well?

**Comment by Chinwendu20** [comment]
> I couldn't find it but can we check the apiVersion and Kind on KubeArmor side as well?

This is the type of the policy Event

image
 
I cannot see any field for apiversion or kind

File: KubeArmor/common/common.go (hunk 1 above)
Comment (Chinwendu20) [reply KubeArmor/common/common.go]: Okay thanks a lot. I will implement the change

**Comment by Chinwendu20** [comment]
Do you know of any other way that I can obtain the apiversion or kind from the kubeamor side?

**Comment by daemon1024** [comment]
It should be fine, let's just add the Name check :)

**Comment by Chinwendu20** [comment]
Hi @daemon1024 I would just check for the Metadata Name. As even empty polices have Metadata as the creation time is always present.

File: KubeArmor/policy/policy.go [hunk 2]
```diff
@@ -38,12 +47,22 @@ func (p *ServiceServer) ContainerPolicy(c context.Context, data *pb.Policy) (*pb
...
+
+		if policyEvent.Object.Metadata.Name != ""{
+
 		p.UpdateHostPolicy(policyEvent)
+
+		}else{
+
+		kg.Warn("Empty Host Policy Event")
+
+		}
```
Comment (daemon1024) [inline KubeArmor/policy/policy.go:73]: Let's add res,Status = 0 as well in the else condition and move the status = 1 to the if condition. Also I would suggest you to run `gofmt` once it will handle the formating for ya!

Comment (Chinwendu20) [reply KubeArmor/policy/policy.go:73]: Okay thanks

Comment (Chinwendu20) [reply KubeArmor/policy/policy.go:73]: okay thanks I have done that

**Review by daemon1024 — APPROVED** [review]
Nice 👌🏽
