### PR TITLE
fix(audit) : readOnly audit alerts

### LINKED ISSUE #1397: Audit based Hardening Policy not giving Alerts upon the Violations - "System and Information Integrity - System Monitoring make files under /dev/"
Bug 1:  The Given Audit based Hardening Policy not giving Alerts upon the Violations - "System and Information Integrity - System Monitoring make files under /dev/"

```sh
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: harden-wordpress-write-under-dev-dir
  namespace: wordpress-mysql
spec:
  action: Audit
  file:
    matchDirectories:
    - dir: /dev/
      readOnly: true
      recursive: true
  message: Alert! File creation under /dev/ directory detected.
  selector:
    matchLabels:
      app: wordpress
  severity: 5
  tags:
  - NIST
  - NIST_800-53_AU-2
  - NIST_800-53_SI-4
  - MITRE
  - MITRE_T1036_masquerading
```

**General Information**

- Environment description  -GKE
- Linux cs-610260858826-default 5.15.120+ #1 SMP Wed Aug 9 09:14:11 UTC 2023 x86_64 GNU/Linux
- Orchestration system version - Client Version: v1.27.4
                                                     Kustomize Version: v5.0.1
                                                     Server Version: v1.27.3-gke.100

- Target pods - wordpress, nginx
- Deployment  Details
```sh 
shanmuga@cloudshell:~ (centering-study-396808)$ kubectl describe deployment wordpress -n wordpress-mysql 
Name:                   wordpress
Namespace:              wordpress-mysql
CreationTimestamp:      Wed, 30 Aug 2023 09:38:49 +0000
Labels:                 app=wordpress
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=wordpress
Replicas:               1 desired | 1 updated | 1 total | 1 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  app=wordpress
  Containers:
   wordpress:
    Image:      wordpress:4.8-apache
    Port:       80/TCP
    Host Port:  0/TCP
    Environment:
      WORDPRESS_DB_HOST:      mysql
      WORDPRESS_DB_PASSWORD:  root-password
    Mounts:                   <none>
  Volumes:                    <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Progressing    True    NewReplicaSetAvailable
  Available      True    MinimumReplicasAvailable
OldReplicaSets:  <none>
NewReplicaSet:   wordpress-7c966b5d85 (1/1 replicas created)
Events:          <none>
```

```sh
shanmuga@cloudshell:~ (centering-study-396808)$ kubectl exec -it wordpress-7c966b5d85-lm5fl -n wordpress-mysql -- bash
root@wordpress-7c966b5d85-lm5fl:/var/www/html# cd /dev
root@wordpress-7c966b5d85-lm5fl:/dev# touch priya
root@wordpress-7c966b5d85-lm5fl:/dev# ls
core  fd  full  mqueue  null  priya  ptmx  pts  random  shm  stderr  stdin  stdout  termination-log  tty  urandom  zero
root@wordpress-7c966b5d85-lm5fl:/dev# touch priya123
root@wordpress-7c966b5d85-lm5fl:/dev# cd core
bash: cd: core: Not a directory
root@wordpress-7c966b5d85-lm5fl:/dev# mkdir shan
root@wordpress-7c966b5d85-lm5fl:/dev# cat shm
cat: shm: Is a directory
root@wordpress-7c966b5d85-lm5fl:/dev# cd shm
root@wordpress-7c966b5d85-lm5fl:/dev/shm# ls
root@wordpress-7c966b5d85-lm5fl:/dev/shm# touch kngofnd
```

 
```sh
shanmuga@cloudshell:~ (centering-study-396808)$ karmor logs
local port to be used for port forwarding kubearmor-relay-5ccb6b6ffb-5rlq5: 32897 
Created a gRPC client (localhost:32897)
Checked the liveness of the gRPC server
Started to watch alerts
^Z
[2]+  Stopped                 karmor logs
```

### PR DESCRIPTION
**Pull request by Prateeknandle**
**Purpose of PR?**:
There was no check for `readOnly` audit events where we set `matchedFlags` to true.

Fixes #1397 

**Does this PR introduce a breaking change?**

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [x] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Review by daemon1024 — CHANGES_REQUESTED** [review]
Please verify owner only rules and, owner and readonly only rules together.

Also let's add test case for this

File: tests/k8s_env/ksp/ksp_test.go [hunk 1]
```diff
@@ -1864,6 +1915,57 @@ var _ = Describe("Ksp", func() {
 
 		})
 
+		It("it can audit access to a dir except readonly access is allowed", func() {
+
+			// Test 1: trying to create a file with directory readonly permissions should generate audit events
+			if strings.Contains(K8sRuntimeEnforcer(), "bpf") {
+				Skip("Skipping due to issue with readonly policies with bpflsm enforcer in this particular testcase we'not getting alert for some reason")
+			}
```
Comment (daemon1024) [inline tests/k8s_env/ksp/ksp_test.go]: This is a audit testcase why skip for bpflsm?

**Review by daemon1024 — CHANGES_REQUESTED** [review]

**Comment by daemon1024** [comment]
Please rebase and squash. Thanks 🙌🏽

File: tests/k8s_env/ksp/ksp_test.go [hunk 2]
```diff
@@ -872,6 +872,57 @@ var _ = Describe("Ksp", func() {
...
+			Expect(res.Found).To(BeTrue())
+
+			// Test 2: readonly access by the owner should be allowed without any audit events
+			// Start KubeArmor Logs
+			err = KarmorLogStart("system", "multiubuntu", "File", ub1)
+			Expect(err).To(BeNil())
+
+			time.Sleep(5 * time.Second) // for policy
+
+			sout, _, err = K8sExecInPod(ub1, "multiubuntu",
```
Comment (PrimalPimmy) [inline tests/k8s_env/ksp/ksp_test.go]: Use the AssertCommand function here instead of K8sExecInPod

File: tests/k8s_env/ksp/ksp_test.go [hunk 3]
```diff
@@ -1733,6 +1784,53 @@ var _ = Describe("Ksp", func() {
...
+			res, err := KarmorGetTargetAlert(5*time.Second, &expect)
+			Expect(err).To(BeNil())
+			Expect(res.Found).To(BeTrue())
+
+			// Test 2: reading the file should result in success without audit events
+			// Start KubeArmor Logs
+			err = KarmorLogStart("system", "multiubuntu", "File", ub4)
+			Expect(err).To(BeNil())
+
+			sout, _, err = K8sExecInPod(ub4, "multiubuntu",
```
Comment (PrimalPimmy) [inline tests/k8s_env/ksp/ksp_test.go]: here too, use assertcommand

**Review by PrimalPimmy — CHANGES_REQUESTED** [review]

File: tests/k8s_env/ksp/ksp_test.go (hunk 3 above)
Comment (Prateeknandle) [reply tests/k8s_env/ksp/ksp_test.go]: why here? we don't have any matching logic here

Comment (daemon1024) [reply tests/k8s_env/ksp/ksp_test.go]: Matching logic could be .* or it could be NotContain (Permission Denied)
Essentially it's asserting whether the command was success or not

File: tests/k8s_env/ksp/ksp_test.go [hunk 4]
```diff
@@ -872,6 +872,55 @@ var _ = Describe("Ksp", func() {
...
+			err = KarmorLogStart("policy", "multiubuntu", "File", ub1)
+			Expect(err).To(BeNil())
+
+			time.Sleep(5 * time.Second) // for policy
+
+			sout, _, err := K8sExecInPod(ub1, "multiubuntu",
+				[]string{"bash", "-c", "touch  /home/user1/new1"})
+			Expect(err).To(BeNil())
+			fmt.Printf("OUTPUT: %s\n", sout)
+
```
Comment (daemon1024) [inline tests/k8s_env/ksp/ksp_test.go]: Do we need sleep here? Isn't this a audit policy?

**Review by daemon1024 — APPROVED** [review]
LGTM, Waiting for tests to pass

**Review by PrimalPimmy — APPROVED** [review]
LGTM :rocket:

**Comment by PrimalPimmy** [comment]
@Prateeknandle could u rebase, then we'll merge
