### PR TITLE
fix(feeder/ci): prevent resource leaks on NewFeeder failure and enable CI coverage metrics

### LINKED ISSUE #2158: Resource leak in NewFeeder: gRPC Listener and LogFile not closed properly
## Bug Report

**Description of the Bug**

The gRPC listener (net.Listener) and the log file (os.OpenFile) are not properly closed in error cases 

the likely reason this was missed out is because the user was expected to call fd.DestroyFeeder()
after creating newFeeder() but fd.DestroyFeeder() cant be called when newFeeder() returns nil when failed

I observed this leak during consecutive test runs, where the resource port remained open leading to conflicts and leftover file descriptors.

```go
...
	// gRPC configuration
	fd.Port = fmt.Sprintf(":%s", cfg.GlobalCfg.GRPC)

	// listen to gRPC port
	listener, err := net.Listen("tcp", fd.Port)
	if err != nil {
		kg.Errf("Failed to listen a port (%s, %s)", fd.Port, err.Error())
		return nil
	}
	fd.Listener = listener

	if cfg.GlobalCfg.GRPC == "0" {
		pidFile, err := os.Create(cfg.PIDFilePath)
		if err != nil {
			kg.Errf("Failed to create file %s", cfg.PIDFilePath)
			return        <<<<< listener not closed, destroy on feeder cant be called after it returns 
		}
....

```

**Expected behavior**

The gRPC listener and log file should be properly closed if NewFeeder() initialization fails.

**Screenshots**
Tests i wrote where first one among three feeder creation was made to fail

Image

**To Reproduce**

write 2 tests: 
make sure the first newFeeder() creation purposely fails (error should be after the listening)
creating the second one normally will cause error "Failed to listen a port" because of resource leak

### PR DESCRIPTION
**Pull request by GAURAV-DEEP01**
#### 1. Resource leak in NewFeeder():
Closes gRPC listener and log file if NewFeeder() fails during initialization.
Previously, errors during initialization left ports and file descriptors open, causing conflicts on consecutive runs.

#### 2. CI Coverage Metrics:
Fixes coverage generation in CI-Network-Tests and CI-Test-UBI-Image workflows and uploads coverage file.
- **Before the fix**: No coverage was recorded (0.0%) because KubeArmor binaries were not built with coverage flags, and coverage files were not collected. [Before Fix](https://github.com/kubearmor/KubeArmor/actions/runs/18398000563/job/52421012173#step:19:1)
- **After the fix**: Proper coverage files are generated, collected, and uploaded by mounting the coverage path.
[After Fix](https://github.com/kubearmor/KubeArmor/actions/runs/18461098410/job/52601429161#step:20:37)

**Purpose of PR?**:
Fixes #2158 (resource leak) and ensures coverage metrics are correctly reported in CI.

**Does this PR introduce a breaking change?**
No

**If the changes in this PR are manually verified, list down the scenarios covered:**

 For Resource leak: 
* Created a test where the first `NewFeeder()` intentionally fails after the listener is created. Verified that the listener is closed and the port is freed.
* Verified that subsequent `NewFeeder()` calls succeed without `"Failed to listen a port"` errors.
* Checked that log file handles are also properly released.

CI Coverage Metrics:
* Coverage metrics are generated, collected, and uploaded correctly in both ci-network-tests and ci-test-ubi-image CI workflows.

**Additional information for reviewer?**
The CI Fixes were added later

**Checklist:**

* [x] Bug fix. Fixes #<issue number>
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] This change requires a documentation update
* [x] PR Title follows the convention of `<type>(<scope>): <subject>`
* [x] Commit has unit tests
* [ ] Commit has integration tests

### CODE REVIEW

**Comment by GAURAV-DEEP01** [comment]
cc @Aryan-sharma11

**Comment by rksharma95** [comment]
@GAURAV-DEEP01 can you please add the unit tests as well that you mentioned in the description. thanks

**Comment by GAURAV-DEEP01** [comment]
Reordered test cases to reproduce the bug

**Comment by GAURAV-DEEP01** [comment]
image

**Comment by GAURAV-DEEP01** [comment]
image

**Comment by GAURAV-DEEP01** [comment]
This PR also fixes the CI coverage issue where metrics were previously 0.0% because the workflow wasn’t using coverage-enabled test images.

[CI workflow Before](https://github.com/kubearmor/KubeArmor/actions/runs/18398000563/job/52421012173#step:19:1)

image

 The updated workflow now uses kubearmor-test and  kubearmor-ubi-test images, mounts a volume for coverage output and extracts/uploads the coverage file. Coverage is now correctly generated and available in both ci-network-tests and ci-test-ubi-image workflows.
 
[CI workflow After](https://github.com/kubearmor/KubeArmor/actions/runs/18461098410/job/52601429161#step:20:37)

image
 
image

**Comment by tesla59** [comment]
hi

**Comment by GAURAV-DEEP01** [comment]
@rksharma95 @Aryan-sharma11 The failing tests doesn't seem to be related to the PR

File: KubeArmor/feeder/feeder_test.go [hunk 1]
```diff
@@ -4,36 +4,220 @@
...
+				cfg.GlobalCfg = cloneConfig()
+				cfg.GlobalCfg.GRPC = "55555"
+
+				tmpFile, err := os.CreateTemp("", "feeder-log-*.log")
+				if err != nil {
+					t.Fatalf("Failed to create temp log file: %v", err)
+				}
+				cfg.GlobalCfg.LogPath = tmpFile.Name()
+
+				tmpFile.Close()
```
Comment (AryanBakliwal) [inline KubeArmor/feeder/feeder_test.go:85]: This temporary file should also be deleted here

**Review by AryanBakliwal — DISMISSED** [review]
LGTM overall, please add the above small change and update the branch

File: KubeArmor/feeder/feeder_test.go (hunk 1 above)
Comment (GAURAV-DEEP01) [reply KubeArmor/feeder/feeder_test.go:85]: yes

**Comment by Aryan-sharma11** [comment]
@GAURAV-DEEP01, kindly squash the commits.

**Review by AryanBakliwal — APPROVED** [review]

**Comment by Aryan-sharma11** [comment]
@GAURAV-DEEP01, kindly explain the CI changes in this PR.

**Comment by GAURAV-DEEP01** [comment]
[Quick view of what was fixed in the CI ](https://github.com/kubearmor/KubeArmor/pull/2159#issuecomment-3399151986)

### CI Coverage Issue (Before)

previously the CI workflows (ci-network-test-ginkgo and ci-test-ubi-image) **did not record any coverage metrics (0.0%)**, even though the tests were running successfully
This happened because

* The KubeArmor binaries were **built without Go coverage flags**
* the test pods **didnt mount any persistent directory** to store the generated .coverprofile files
* as a result even if the tests executed inside cluster, **the coverage data would have never left the container** 


### CI Fixes and Improvements (Now)

the updated workflow fixes this by enabling proper **coverage generation, collection, and upload**

1. **Build-time**
   The environment variable IS_COVERAGE=true is exported before running build_kubearmor.sh
   this ensures all KubeArmor test binaries (kubearmor-test, kubearmor-ubi-test) are built with go coverage flags so runtime coverage data is produced during tests

2. **Mounting coverage storage**
   After KubeArmor is deployed in the test cluster, the workflow patches the DaemonSet to mount a host directory /coverage
   The KubeArmor container writes its coverage output to this shared path

   -test.coverprofile=/coverage/coverage_k8s_${{ matrix.os }}_${{ matrix.runtime }}.out

   This guarantees the file persists on the host even after the container exits

3. **kill and flush coverage**
   Once the Ginkgo network tests complete the workflow kills the process with a SIGINT signal to the KubeArmor process inside the pod
   This allows Go to flush and write the coverage data to the /coverage folder

4. **Coverage extraction and upload**
   The workflow waits for the coverage file to appear, copies it to the runner workspace and uploads it as
   
   `coverage_k8s_<os>_<runtime>.out`

5. **Other reliability updates** (refered from ci-test-ginkgo.yaml)

   * Added explicit image tagging for Podman in CRI-O runs 
   * Cleaned up Docker and Buildx caches to prevent leftover images


### Finally

* Coverage is now **accurately generated and reported** for all runtime combinations in CI
* The workflows no longer show 0.0% coverage
* Coverage artifacts are uploaded and visible on GitHub Actions artifacts

**Review by Aryan-sharma11 — APPROVED** [review]
