### PR TITLE
fix(core): use informers to watch for pods

### LINKED ISSUE #2074: Memory leak in AppArmor daemonset
## Bug Report

**General Information**

- Environment description (GKE, VM-Kubeadm, vagrant-dev-env, minikube, microk8s, ...):
AKS
- Kernel version (run `uname -a`):
```
System Info:
  Kernel Version:             5.15.0-1084-azure
  OS Image:                   Ubuntu 22.04.5 LTS
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  containerd://1.7.27-1
  Kubelet Version:            v1.30.11
  Kube-Proxy Version:         v1.30.11
```
- Orchestration system version in use (e.g. `kubectl version`, ...)
1.30.11
- Link to relevant artifacts (policies, deployments scripts, ...)
- Target containers/pods
`kubearmor-apparmor-containerd` pod, `kubearmor` container

**To Reproduce**

1. Deploy `kubearmor` to cluster without BPF LSM enabled on nodes
2. Observe that `kubearmor` container of `kubearmor-apparmor-containerd` daemonset repeatedly grows in memory until it OOMs

**Expected behavior**
`kubearmor-apparmor-containerd` daemonset runs with bounded memory

**Screenshots**

working set memory available, as captured by the following query:
```
container_spec_memory_limit_bytes{job=~"kubelet",namespace=~"kubearmor",container=~"kubearmor",pod=~"kubearmor-apparmor-containerd-([0-9]+|[0-9a-f]+-[0-9a-z]{5}|[0-9a-z]{5})"} - container_memory_working_set_bytes{job=~"kubelet",namespace=~"kubearmor",container=~"kubearmor",pod=~"kubearmor-apparmor-containerd-([0-9]+|[0-9a-f]+-[0-9a-z]{5}|[0-9a-z]{5})"}`)
```

(note that `container_memory_working_set_bytes` hitting the limit [directly correlates with OOMs](https://faun.pub/how-much-is-too-much-the-linux-oomkiller-and-used-memory-d32186f29c9d))

Image

```
# event from kubectl describe on a node with a recent oomkill
  Warning  OOMKilling  49m   kernel-monitor  Memory cgroup out of memory: Killed process 1869499 (kubearmor) total-vm:2327500kB, anon-rss:1032208kB, file-rss:75000kB, shmem-rss:0kB, UID:0 pgtables:2288kB oom_score_adj:968
```

### PR DESCRIPTION
**Pull request by rksharma95**
on AKS cluster only it's been observed that using https stream connection to watch for pods introducing an undefined behaviour and result in a memory leak when connection with kubeapi server interrupts and retries to connect frequently.

**Purpose of PR?**:
image

Fixes #2074

**Does this PR introduce a breaking change?**
No
**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [x] Bug fix. Fixes #2074 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

File: KubeArmor/core/kubeUpdate.go [hunk 1]
```diff
@@ -594,391 +598,411 @@ func (dm *KubeArmorDaemon) HandleUnknownNamespaceNsMap(container *tp.Container)
...
+	}
 
-				// exception: kubernetes app
-				if pod.Metadata["namespaceName"] == "kube-system" {
-					pod.Annotations["kubearmor-policy"] = "audited"
-				}
+	// exception: kubearmor
+	// if _, ok := pod.Labels["kubearmor-app"]; ok {
+	// 	pod.Annotations["kubearmor-policy"] = "audited"
+	// }
```
Comment (Aryan-sharma11) [inline KubeArmor/core/kubeUpdate.go:731]: should this be commented?

Comment (rksharma95) [reply KubeArmor/core/kubeUpdate.go:731]: it was done as part of https://github.com/kubearmor/KubeArmor/pull/1831. do you think we can remove all of these exceptions here if it's being handled as part of ignoreNamespace?

**Review by Aryan-sharma11 — APPROVED** [review]

**Review by rootxrishabh — APPROVED** [review]
