### PR TITLE
deploy/core: kubearmor for GKE latest COS images

### LINKED ISSUE #579: Kubearmor pod stuck in ContainerCreating with GKE Rapid Release Version
## Bug Report

**General Information**

- Environment description (GKE, VM-Kubeadm, vagrant-dev-env, minikube, microk8s, ...)
        `GKE Rapid Release Version 1.22.3-gke.700`
- Kernel version (run `uname -a`)

        Linux gke-cluster-1-default-pool-7b6c3cc6-hlf8 5.10.68+ #1 SMP Wed Oct 6 22:30:49 UTC 2021 x86_64 Intel(R) Xeon(R) CPU @ 2.20GHz GenuineIntel GNU/Linux
- Orchestration system version in use (e.g. `kubectl version`, ...)
    ```
    Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3-gke.700", GitCommit:"e21de5d6cf1b351bc99285c3c762098b8617b773", GitTreeState:"clean", BuildDate:"2021-11-05T09:25:32Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}
- Link to relevant artifacts (policies, deployments scripts, ...)
- Target containers/pods
    ```ubuntu 20.04 ```

**To Reproduce**

1. Install KubeArmor using CLI
```karmor install ```
2. Check for pod status
```kubectl get po -A -lkubearmor-app=kubearmor -o wide```

**Current behavior**

The pods are stuck in Containercreating phase with kubelet error `FailedMount`
```
kubectl get po -A -lkubearmor-app=kubearmor                                 
NAMESPACE     NAME              READY   STATUS              RESTARTS   AGE
kube-system   kubearmor-f2qvs   0/1     ContainerCreating   0          27m
kube-system   kubearmor-fjwb6   0/1     ContainerCreating   0          27m
kube-system   kubearmor-w5rsj   0/1     ContainerCreating   0          27m
```
```
kubectl -n kube-system describe $(kubectl get po -A -lkubearmor-app=kubearmor -o name)
Name:         kubearmor-f2qvs
Namespace:    kube-system
Priority:     0
Node:         gke-cluster-1-default-pool-c0d7970d-1f2f/10.128.0.57
Start Time:   Fri, 28 Jan 2022 00:43:17 +0530
Labels:       controller-revision-hash=7d45978987
              kubearmor-app=kubearmor
              pod-template-generation=1
Annotations:  container.apparmor.security.beta.kubernetes.io/kubearmor: unconfined
Status:       Pending
IP:           10.128.0.57
IPs:
  IP:           10.128.0.57
Controlled By:  DaemonSet/kubearmor
Containers:
  kubearmor:
    Container ID:  
    Image:         kubearmor/kubearmor:latest
    Image ID:      
    Port:          32767/TCP
    Host Port:     32767/TCP
    Args:
      -gRPC=32767
      -logPath=/tmp/kubearmor.log
      -enableKubeArmorHostPolicy
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Liveness:       exec [/bin/bash -c if [ -z $(pgrep kubearmor) ]; then exit 1; fi;] delay=60s timeout=1s period=10s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /etc/apparmor.d from etc-apparmor-d-path (rw)
      /lib/modules from lib-modules-path (ro)
      /media/root/etc/os-release from os-release-path (ro)
      /run/containerd from containerd-storage-path (ro)
      /sys/fs/bpf from sys-fs-bpf-path (rw)
      /sys/kernel/debug from sys-kernel-debug-path (rw)
      /usr/src from usr-src-path (ro)
      /var/lib/docker from docker-storage-path (ro)
      /var/run/containerd/containerd.sock from containerd-sock-path (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-zbbpw (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  usr-src-path:
    Type:          HostPath (bare host directory volume)
    Path:          /usr/src
    HostPathType:  Directory
  lib-modules-path:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  Directory
  sys-fs-bpf-path:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/fs/bpf
    HostPathType:  Directory
  sys-kernel-debug-path:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/kernel/debug
    HostPathType:  Directory
  os-release-path:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/os-release
    HostPathType:  File
  etc-apparmor-d-path:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/apparmor.d
    HostPathType:  DirectoryOrCreate
  containerd-sock-path:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/containerd/containerd.sock
    HostPathType:  Socket
  containerd-storage-path:
    Type:          HostPath (bare host directory volume)
    Path:          /run/containerd
    HostPathType:  DirectoryOrCreate
  docker-storage-path:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/docker
    HostPathType:  DirectoryOrCreate
  kube-api-access-zbbpw:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason       Age                    From               Message
  ----     ------       ----                   ----               -------
  Normal   Scheduled    28m                    default-scheduler  Successfully assigned kube-system/kubearmor-f2qvs to gke-cluster-1-default-pool-c0d7970d-1f2f
  Warning  FailedMount  26m                    kubelet            Unable to attach or mount volumes: unmounted volumes=[usr-src-path], unattached volumes=[sys-fs-bpf-path containerd-storage-path kube-api-access-zbbpw usr-src-path docker-storage-path sys-kernel-debug-path lib-modules-path os-release-path etc-apparmor-d-path containerd-sock-path]: timed out waiting for the condition
  Warning  FailedMount  24m                    kubelet            Unable to attach or mount volumes: unmounted volumes=[usr-src-path], unattached volumes=[sys-kernel-debug-path docker-storage-path kube-api-access-zbbpw containerd-storage-path lib-modules-path containerd-sock-path usr-src-path sys-fs-bpf-path os-release-path etc-apparmor-d-path]: timed out waiting for the condition
  Warning  FailedMount  22m                    kubelet            Unable to attach or mount volumes: unmounted volumes=[usr-src-path], unattached volumes=[sys-fs-bpf-path sys-kernel-debug-path usr-src-path os-release-path containerd-sock-path containerd-storage-path docker-storage-path kube-api-access-zbbpw lib-modules-path etc-apparmor-d-path]: timed out waiting for the condition
  Warning  FailedMount  19m                    kubelet            Unable to attach or mount volumes: unmounted volumes=[usr-src-path], unattached volumes=[os-release-path usr-src-path docker-storage-path containerd-storage-path containerd-sock-path kube-api-access-zbbpw lib-modules-path sys-fs-bpf-path sys-kernel-debug-path etc-apparmor-d-path]: timed out waiting for the condition
  Warning  FailedMount  17m                    kubelet            Unable to attach or mount volumes: unmounted volumes=[usr-src-path], unattached volumes=[containerd-sock-path docker-storage-path lib-modules-path os-release-path etc-apparmor-d-path usr-src-path containerd-storage-path sys-fs-bpf-path sys-kernel-debug-path kube-api-access-zbbpw]: timed out waiting for the condition
  Warning  FailedMount  15m                    kubelet            Unable to attach or mount volumes: unmounted volumes=[usr-src-path], unattached volumes=[sys-fs-bpf-path containerd-sock-path kube-api-access-zbbpw usr-src-path os-release-path lib-modules-path sys-kernel-debug-path etc-apparmor-d-path containerd-storage-path docker-storage-path]: timed out waiting for the condition
  Warning  FailedMount  13m                    kubelet            Unable to attach or mount volumes: unmounted volumes=[usr-src-path], unattached volumes=[containerd-sock-path containerd-storage-path docker-storage-path usr-src-path lib-modules-path os-release-path kube-api-access-zbbpw sys-fs-bpf-path sys-kernel-debug-path etc-apparmor-d-path]: timed out waiting for the condition
  Warning  FailedMount  10m                    kubelet            Unable to attach or mount volumes: unmounted volumes=[usr-src-path], unattached volumes=[kube-api-access-zbbpw usr-src-path sys-kernel-debug-path containerd-storage-path containerd-sock-path etc-apparmor-d-path docker-storage-path sys-fs-bpf-path lib-modules-path os-release-path]: timed out waiting for the condition
  Warning  FailedMount  6m14s (x2 over 8m32s)  kubelet            (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[usr-src-path], unattached volumes=[os-release-path etc-apparmor-d-path containerd-storage-path kube-api-access-zbbpw sys-kernel-debug-path lib-modules-path containerd-sock-path docker-storage-path sys-fs-bpf-path usr-src-path]: timed out waiting for the condition
  Warning  FailedMount  2m11s (x21 over 28m)   kubelet            MountVolume.SetUp failed for volume "usr-src-path" : hostPath type check failed: /usr/src is not a directory
  ```

**Expected behavior**

Kubearmor pods upd and running

### PR DESCRIPTION
**Pull request by nyrahul**
* latest GKE COS images do not have path for /usr/src.
* deploygen updated to create kubearmor.yamls accordingly

Detailed description:
GKE supports multiple images types, viz COS and non-COS(Ubuntu, Debian
etc). In case of non-COS images, the `/usr/src` contains the kernel
headers. In case of COS, kubearmor internally downloads the kernel
headers but still it used to mount `/usr/src` since we used a single yaml
for COS and non-COS images. In the latest releases of COS images
(for e.g., 1.22.6-gke-1000), the `/usr/src` folder is no longer
present. The current changes now mounts /usr to /opt/hostusr folder for
GKE (only). The kubearmor code internally sets `BCC_KERNEL_SOURCE` to
`/media/root/usr/src/linux-headers-KERNELVER`.

Fixes #579

Signed-off-by: Rahul Jadhav <nyrahul@gmail.com>

### CODE REVIEW

File: KubeArmor/monitor/systemMonitor.go [hunk 1]
```diff
@@ -226,8 +221,20 @@ func (mon *SystemMonitor) InitBPF() error {
...
-
-				mon.IsCOS = true
+			} else {
+				// In case of GKE COS release >= 1.22, the base OS img does not
+				// contain /usr/src folder. Thus we now mount /usr folder to
+				// /opt/hostusr folder in kubearmor for GKE. The following code
+				// checks whether the /opt/hostusr/src/kernel-hdrs path exists
+				// and uses it for BCC kernel source, if present.
+				lklhdrpath := "/opt/hostusr/src/linux-headers-" + mon.KernelVersion
+				mon.Logger.Printf("chking if kernel headers path (%s) exists", lklhdrpath)
```
Comment (nam-jaehyun) [inline KubeArmor/monitor/systemMonitor.go]: chking -> checking

Comment (nyrahul) [reply KubeArmor/monitor/systemMonitor.go]: Handled

**Review by nam-jaehyun — APPROVED** [review]
Good to merge it!

File: deployments/get/objects.go [hunk 2]
```diff
@@ -352,6 +352,38 @@ func GetHostPolicyManagerDeployment(namespace string) *appsv1.Deployment {
 	}
 }
 
+var gkeHostUsrVolMnt = corev1.VolumeMount{
+	Name:      "usr-src-path", // /usr -> /media/root/usr (read-only) check issue #579 for details
+	MountPath: "/media/root/usr",
+	ReadOnly:  true,
+}
+
+var gkeHostUsrVol = corev1.Volume{ // check #579 why GKE is handled separately
```
Comment (daemon1024) [inline deployments/get/objects.go]: We should keep environment specific mounts in defaultConfigs Map. https://github.com/kubearmor/KubeArmor/blob/925a26abe2d61d17f364d5f942184a4a0b7671c3/deployments/get/defaults.go#L296

Comment (nyrahul) [reply deployments/get/objects.go]: Interesting.

So in this case, I have to copy VolumeMounts and Volumes that are "gke" specific in "gke" and also copy the default ones in every other case (k3s, eks, minikube....) ... is this understanding correct?

Comment (nyrahul) [reply deployments/get/objects.go]: Handled.

**Review by daemon1024 — APPROVED** [review]
LGTM
