### PR TITLE
Align Logs output with ReadOnly/OwnerOnly options

### LINKED ISSUE #352: Fix readOnly policy match condition
## Bug Report
**General Information**

- Environment: vagrant-dev-env(kubearmor-dev-next)
- Kernel version: `Linux kubearmor-dev-next 5.13.0-14-generic #14-Ubuntu SMP Mon Aug 2 12:43:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, ...)
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)
- Target containers/pods

**To Reproduce**

1. Apply a KubeArmorPolicy with action as `Audit` or `Allow` having `readOnly` for some file path. For example-
```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-4-file-path-readonly-audit
  namespace: multiubuntu
spec:
  severity: 10
  message: "a critical file was accessed"
  tags:
  - WARNNING
  selector:
    matchLabels:
      container: ubuntu-4
  file:
    matchPaths:
    - path: /credentials/password # echo "test" >> /credentials/password (should get log, write op)
      readOnly: true # cat /credentials/password (should get no log, readOnly op)
  action:
    Audit
```
2. Perform read operation on that file using `cat <file_path>` command inside the corresponding pod. 
```
vagrant@kubearmor-dev-next:~$ kubectl exec -ti -n multiubuntu ubuntu-4-deployment-666b6dd9-mfmxl -- bash
root@ubuntu-4-deployment-666b6dd9-mfmxl:/# cat /credentials/password
password file
```
3. Check generated logs. There will be a MatchedPolicy log generated for the read operation just performed. Notice that there is a `O_RDONLY` flag in the log.
```
Policy","source":"/bin/cat /credentials/password","operation":"File","resource":"/credentials/password","data":"syscall=SYS_OPENAT fd=-100 flags=O_RDONLY","action":"Audit","result":"Passed"}
```
**Expected behavior**
We shouldn't get MatchedPolicy log for read operation when the event has O_RDONLY flag set.

### LINKED ISSUE #353: Fix ownerOnly policy match condition for audit policies
## Bug Report
**General Information**

- Environment: vagrant-dev-env(kubearmor-dev-next)
- Kernel version: `Linux kubearmor-dev-next 5.13.0-14-generic #14-Ubuntu SMP Mon Aug 2 12:43:35 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Orchestration system version in use (e.g. `kubectl version`, ...)
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:45:37Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.4", GitCommit:"3cce4a82b44f032d0cd1a1790e6d2f5a55d20aae", GitTreeState:"clean", BuildDate:"2021-08-11T18:10:22Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}
```
- Link to relevant artifacts (policies, deployments scripts, ...)
- Target containers/pods

**To Reproduce**

1. Apply a KubeArmorPolicy with action as `Audit` having `ownerOnly` for some file path(or some process path). For example-
```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-ubuntu-3-file-path-owner-audit
  namespace: multiubuntu
spec:
  severity: 7
  selector:
    matchLabels:
      container: ubuntu-3
  file:
    matchPaths:
    - path: /home/user1/secret_data1.txt  
      ownerOnly: true
  action:
    Audit
```
2. Switch to that user using `su - <user_name>`. Access that file.
```
vagrant@kubearmor-dev-next:~$ kubectl exec -ti -n multiubuntu ubuntu-3-deployment-59bf5f5564-tsft2 -- bash
root@ubuntu-3-deployment-59bf5f5564-tsft2:/# su - user1
user1@ubuntu-3-deployment-59bf5f5564-tsft2:~$ echo "this is secret" >> secret_data1.txt 
user1@ubuntu-3-deployment-59bf5f5564-tsft2:~$ ls -l
total 16
-rwxrwxr-x 1 user1 user1 8304 Jul 13 10:15 hello
-rw-rw-r-- 1 user1 user1   15 Sep 15 07:29 secret_data1.txt
```
3. Check UID of the owner using `cat /etc/passwd | grep <user_name>` . Here it's 1000.
```
user1@ubuntu-3-deployment-59bf5f5564-tsft2:~$ cat /etc/passwd|grep user1
user1:x:1000:1000::/home/user1:/bin/bash
```
4. Check generated logs. There will be a MatchedPolicy log generated for the echo command used by owner in step 2. Notice that the UID is 1000 flag in the log.
```
{"timestamp":1631695097,"updatedTime":"2021-09-15T08:38:17.719589Z","hostName":"kubearmor-dev-next","namespaceName":"multiubuntu","podName":"ubuntu-3-deployment-59bf5f5564-tsft2","containerID":"e928f60608f10f11fd79903458b9658515640d0721900df9c0c3b6e3b01478ee","containerName":"ubuntu-3-container","hostPid":99747,"ppid":271,"pid":279,"uid":1000,"policyName":"ksp-ubuntu-3-file-path-owner-audit","severity":"7","type":"MatchedPolicy","source":"/bin/cat /home/user1/secret_data1.txt","operation":"File","resource":"/home/user1/secret_data1.txt","data":"syscall=SYS_OPENAT fd=-100 flags=O_RDONLY","action":"Audit","result":"Passed"}
```
**Expected behavior**
We shouldn't get MatchedPolicy log for owner file accesses as it is permitted in the policy and is not a violation. This needs to be ensured for both Process and File ownerOnly operations.

### PR DESCRIPTION
**Pull request by elfadel**
- [x] Cover KubeArmor in Host case
- [x] Cover KubeArmor in Docker case
- [x] Cover KubeArmor in Containerd case (in PR #454).

Fixes kubearmor/KubeArmor#352, fixes kubearmor/KubeArmor#353.

### CODE REVIEW

File: KubeArmor/feeder/policyMatcher.go [hunk 1]
```diff
@@ -31,7 +33,19 @@ func getProtocolFromName(proto string) string {
 	}
 }
 
-// getOperationAndCapabilityFromName
+func getFileProcessUID(path string) string {
```
Comment (nam-jaehyun) [inline KubeArmor/feeder/policyMatcher.go:36]: How can we get the process UID?

File: KubeArmor/core/dockerHandler.go [hunk 2]
```diff
@@ -114,6 +114,8 @@ func (dh *DockerHandler) GetContainerInfo(containerID string) (tp.Container, err
 	container.ContainerID = inspect.ID
 	container.ContainerName = strings.TrimLeft(inspect.Name, "/")
 
+	container.MergedDir = inspect.GraphDriver.Data["MergedDir"]
```
Comment (nam-jaehyun) [inline KubeArmor/core/dockerHandler.go:117]: Is it possible to access the path inside a container? is this path for the host?

**Comment by nam-jaehyun** [comment]
@elfadel did you test your code in a container?

```
$ cd KubeArmor/KubeArmor/build
$ ./build_kubearmor.sh test
$ kubectl apply -f kubearmor-test.yaml
```

Please check if your change works in the KubeArmor container.

**Comment by dku-boanlab** [comment]
@elfadel instead of docker, how it can work in the case of containerd?

**Comment by elfadel** [comment]
> @elfadel instead of docker, how it can work in the case of containerd?

@nam-jaehyun I will update the containerdHandler in the next commit.

File: KubeArmor/core/dockerHandler.go (hunk 2 above)
Comment (elfadel) [reply KubeArmor/core/dockerHandler.go:117]: That is the point. For now, this path is only accessible when the KubeArmor is running inside a host instead of a container.

File: KubeArmor/feeder/policyMatcher.go (hunk 1 above)
Comment (elfadel) [reply KubeArmor/feeder/policyMatcher.go:36]: The owner of the executable file is the UID. Nope? In the same as a simple file.
