### PR TITLE
[bugfix] fix security profile clash 

### LINKED ISSUE #700: security profile clash when namespace and container-name is same
## Bug Report

kubearmor does not handle properly the situation where there is multiple containers with the same name in the same namespace ( this situation is common when using charts e.g gitlab autodevops) which results in unexpected behavior (policies are not enforced, policies are being applied to wrong containers etc...).

<details><summary>Sample Deployment with same container name (deploy.yaml)</summary>
<p>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp1
spec:
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command:
          - "bash"
        args:
          - "-c"
          - "sleep infinity"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp2
spec:
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command:
          - "bash"
        args:
          - "-c"
          - "sleep infinity"
```

</p>
</details>

<details><summary>Security policy for myapp1 deployment (myapp1-policy.yaml)</summary>
<p>

```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: policy1
spec:
  selector:
    matchLabels:
      app: myapp1
  process:
    matchPaths:
    - path: /usr/bin/ls
  action:
    Block
```
</p>
</details>

<details><summary>Security policy for myapp2 deployment (myapp2-policy.yaml)</summary>
<p>

```yaml
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: policy2
spec:
  selector:
    matchLabels:
      app: myapp2
  process:
    matchPaths:
    - path: /usr/bin/cat
  action:
    Block
```
</p>
</details>

**General Information**

- Environment description: Any
- Kernel version: ANY
- Orchestration system version in use (e.g. `kubectl version`, ...): ANY
- Link to relevant artifacts (policies, deployments scripts, ...): Given in the description above

**To Reproduce**

1. `kubectl apply -f deploy.yaml`
2. `kubectl apply -f myapp1-policy.yaml`

This policy should impact only myapp1, but currently this will also apply the rules to myapp2.

**What is the root cause?**
Currently, we create an apparmor profile using following template `kubearmor-NAMESPACE-CONTAINERNAME`. Thus if there are multiple deployments in the same namespace having same containername then it would apply to all the similar deployments.

**Expected behavior**

Applying `myapp1-policy.yaml` should not impact myapp2 deployment.

**Possible Solution**

Add pod name (without instance id) to the security profile template name for eg. `kubearmor-NAMESPACE-PODNAME-CONTAINERNAME`.

Credits to @achrefbensaad for discovering this issue and reporting it in detail on slack. Thanks

### PR DESCRIPTION
**Pull request by DelusionalOptimist**
Signed-off-by: Rudraksh Pareek <rudraksh@accuknox.com>

Scenarios:
- [x] Deploy kubearmor then deploy pods
- [x] Deploy workloads then deploy kubearmor
- [x] The profile name has deployment's name and is unaffected by changing template hash of pods
- [x]  Workloads annotated by older version of kubearmor comply with these changes. (Handling update)

TODO:
- [x] Update annontations controller to use similar naming convention

This PR fixes #700

### CODE REVIEW

**Comment by DelusionalOptimist** [comment]
To be addressed later. Closing for now.

File: KubeArmor/core/kubeUpdate.go [hunk 1]
```diff
@@ -456,36 +457,42 @@ func (dm *KubeArmorDaemon) WatchK8sPods() {
...
+
 					if event.Object.ObjectMeta.OwnerReferences[0].Kind == "ReplicaSet" {
 						deploymentName := K8s.GetDeploymentNameControllingReplicaSet(pod.Metadata["namespaceName"], event.Object.ObjectMeta.OwnerReferences[0].Name)
 						if deploymentName != "" {
 							pod.Metadata["deploymentName"] = deploymentName
 						}
+
+						// if it belongs to a replicaset, we also remove the pod template hash
+						podTemplateHashSuffix := fmt.Sprintf("-%s", pod.Labels["pod-template-hash"])
+						pod.Metadata["ownerName"] = strings.TrimSuffix(event.Object.ObjectMeta.OwnerReferences[0].Name, podTemplateHashSuffix)
```
Comment (nyrahul) [inline KubeArmor/core/kubeUpdate.go]: When I checked my sample deployment, I have a pod that was instantiated with name `wordpress-54dd4449df-wq7ql` ... but the `pod-template-hash` was only `54dd4449df`. `TrimSuffix` won't be able to trim in this case.

```
vagrant@kubearmor-dev:~/KubeArmor/tests$ kubectl describe pod -n wordpress-mysql wordpress-54dd4449df-wq7ql
Name:         wordpress-54dd4449df-wq7ql
Namespace:    wordpress-mysql
Priority:     0
Node:         kubearmor-dev/10.0.2.15
Start Time:   Wed, 06 Jul 2022 07:25:24 +0000
Labels:       app=wordpress
              pod-template-hash=54dd4449df
Annotations:  container.apparmor.security.beta.kubernetes.io/wordpress: localhost/kubearmor-wordpress-mysql-wordpress
              kubearmor-policy: enabled
Status:       Running
IP:           10.0.0.69
IPs:
  IP:           10.0.0.69
Controlled By:  ReplicaSet/wordpress-54dd4449df
Containers:
  wordpress:
    Container ID:   docker://b503dfed67c4ec54c01b9f91437a089bf44913092bd1da66b38f43c1a7f94b32
    Image:          wordpress:4.8-apache
    Image ID:       docker-pullable://wordpress@sha256:6216f64ab88fc51d311e38c7f69ca3f9aaba621492b4f1fa93ddf63093768845
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Wed, 06 Jul 2022 07:25:32 +0000
    Ready:          True
    Restart Count:  0
    Environment:
      WORDPRESS_DB_HOST:      mysql
      WORDPRESS_DB_PASSWORD:  root-password
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-b4j9b (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  kube-api-access-b4j9b:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>
```

**Review by nyrahul — CHANGES_REQUESTED** [review]
Thanks for handling this on prio. Please find my review comment.

File: KubeArmor/core/kubeUpdate.go (hunk 1 above)
Comment (nyrahul) [reply KubeArmor/core/kubeUpdate.go]: I am mistaken here. The name used is from replicaset which is in the form of `wordpress-54dd4449df`.

Comment (DelusionalOptimist) [reply KubeArmor/core/kubeUpdate.go]: :white_check_mark:

**Comment by DelusionalOptimist** [comment]
@nyrahul @achrefbensaad About the annotation controller.
I was looking back and in #360  we wanted to move the pod annotation logic entirely to the annotations controller, however we still have some of it in kubearmor. Need to know this so as to decide where these changes belong :thinking:

**Review by daemon1024 — COMMENTED** [review]
LGTM

> Workloads annotated by older version of kubearmor comply with these changes. (Handling update)

Thhis would be a breaking change right? 

> I was looking back and in https://github.com/kubearmor/KubeArmor/issues/360 we wanted to move the pod annotation logic entirely to the annotations controller, however we still have some of it in kubearmor.

AFAIK Annotation handling inside KubeArmor is fallback if the controller is not present.

**Comment by DelusionalOptimist** [comment]
> Thhis would be a breaking change right?

Yes @daemon1024, a breaking change. Described more in - https://github.com/kubearmor/KubeArmor/issues/700#issuecomment-1175797617.

> AFAIK Annotation handling inside KubeArmor is fallback if the controller is not present.

Then it needs to go in both the places ig :thinking:

File: KubeArmor/core/kubeUpdate.go [hunk 2]
```diff
@@ -456,36 +457,42 @@ func (dm *KubeArmorDaemon) WatchK8sPods() {
...
+				pod.Labels = map[string]string{}
+				for k, v := range event.Object.Labels {
+					if k == "pod-template-generation" {
+						continue
+					}
+
+					if k == "controller-revision-hash" {
+						continue
+					}
+					pod.Labels[k] = v
```
Comment (nyrahul) [inline KubeArmor/core/kubeUpdate.go]: The labels that are added as part of pod.Labels are shipped in every alert/telemetry. Sending `pod-template-hash` in such telemetry events does not make sense.
Can you check with these changes if the pod-labels (in json format) now contains `pod-template-hash` as well?

**Review by nyrahul — COMMENTED** [review]
Please check one inline comment.

File: KubeArmor/core/kubeUpdate.go (hunk 2 above)
Comment (DelusionalOptimist) [reply KubeArmor/core/kubeUpdate.go]: Yeah they do 
```
{"Timestamp":1657109207,"UpdatedTime":"2022-07-06T12:06:47.678678Z","ClusterName":"default","HostName":"pingu-vm","NamespaceName":"default","PodName":"myapp1-5dddbf7478-8p8r8","Labels":"app=myapp1,pod-template-hash=5dddbf7478","ContainerID":"b529bd2f301f6308334761c792851f8adbe7dae2cffc560159e5bce2cf9649a9","ContainerName":"ubuntu","ContainerImage":"ubuntu:latest@sha256:b6b83d3c331794420340093eb706a6f152d9c1fa51b262d9bf34594887c2c7ac","HostPPID":2843709,"HostPID":2843839,"PPID":7,"PID":15,"ParentProcessName":"/usr/bin/bash","ProcessName":"/usr/bin/ls","PolicyName":"policy1","Severity":"1","Type":"MatchedPolicy","Source":"/usr/bin/bash","Operation":"Process","Resource":"/usr/bin/ls --color=auto","Data":"syscall=SYS_EXECVE","Enforcer":"AppArmor","Action":"Block","Result":"Permission denied"}
```

Comment (DelusionalOptimist) [reply KubeArmor/core/kubeUpdate.go]: No worries, we only need it once anyways. Won't use this map :+1:

**Comment by DelusionalOptimist** [comment]
Folks, I've tested this out with deployments (with multiple replicas), daemonsets and static pods. Lmk if some resource other than these might behave differently.
Also, as we discussed, I tried the update scenario with `karmor uninstall --force` and installing kubearmor after that, we do get profiles with the new convention and enforcement works as expected. However, one thing to note is that the `--force` flag only removes annotations on pods owned by deployments.

**Comment by nyrahul** [comment]
> Folks, I've tested this out with deployments (with multiple replicas), daemonsets and static pods. Lmk if some resource other than these might behave differently. Also, as we discussed, I tried the update scenario with `karmor uninstall --force` and installing kubearmor after that, we do get profiles with the new convention and enforcement works as expected. However, one thing to note is that the `--force` flag only removes annotations on pods owned by deployments.

I guess your point is that the old apparmor policies with old names are still retained in the `/etc/apparmor.d` even though the new ones are created. I believe that should be fine.

File: pkg/KubeArmorAnnotation/handlers/pod_mutation.go [hunk 3]
```diff
@@ -113,6 +114,21 @@ func (a *PodAnnotator) InjectDecoder(d *admission.Decoder) error {
...
+		podOwnerName = pod.ObjectMeta.OwnerReferences[0].Name
+
+		if pod.ObjectMeta.OwnerReferences[0].Kind == "ReplicaSet" {
+			podTemplateHashSuffix := fmt.Sprintf("-%s", pod.ObjectMeta.Labels["pod-template-hash"])
+			podOwnerName = strings.TrimSuffix(podOwnerName, podTemplateHashSuffix)
+		}
+	} else {
+		podOwnerName = pod.ObjectMeta.Name
+	}
+	fmt.Println("podOwnerName is : ", podOwnerName)
```
Comment (nyrahul) [inline pkg/KubeArmorAnnotation/handlers/pod_mutation.go]: Lets use the normal logging APIs.

File: KubeArmor/core/kubeUpdate.go [hunk 4]
```diff
@@ -486,6 +476,29 @@ func (dm *KubeArmorDaemon) WatchK8sPods() {
 					pod.Labels[k] = v
 				}
 
+				if len(event.Object.ObjectMeta.OwnerReferences) > 0 {
+					// pod is owned by a replicaset, daemonset etc thus we use parent object's name
+					pod.Metadata["ownerName"] = event.Object.ObjectMeta.OwnerReferences[0].Name
```
Comment (nyrahul) [inline KubeArmor/core/kubeUpdate.go]: Is it necessary to keep the `ownerName` as part of the `pod.Metadata[]`?
Can we keep it as a local var in the function? I am worried someone might start using `pod.Metadata["ownerName"]` it in the future and it might not be filled up in all cases.

**Review by nyrahul — CHANGES_REQUESTED** [review]

File: KubeArmor/core/kubeUpdate.go [hunk 5]
```diff
@@ -486,6 +476,29 @@ func (dm *KubeArmorDaemon) WatchK8sPods() {
 					pod.Labels[k] = v
 				}
 
+				if len(event.Object.ObjectMeta.OwnerReferences) > 0 {
```
Comment (nyrahul) [inline KubeArmor/core/kubeUpdate.go]: what happens if there are multiple event.Object.ObjectMeta.OwnerReferences .. currently we are using ref at index 0 .. I am just worried that we may not know which index holds the right ref that we may be interested in.

Comment (DelusionalOptimist) [reply KubeArmor/core/kubeUpdate.go]: @nyrahul please take a look now.

Comment (DelusionalOptimist) [reply KubeArmor/core/kubeUpdate.go]: We go through all OwnerReferences and use https://github.com/kubernetes/design-proposals-archive/blob/main/api-machinery/controller-ref.md#api to conclude whether a reference is to the pod's managing controller.
There can be only one controller reference per pod.

File: pkg/KubeArmorAnnotation/handlers/pod_mutation.go [hunk 6]
```diff
@@ -113,6 +114,27 @@ func (a *PodAnnotator) InjectDecoder(d *admission.Decoder) error {
 // == Add AppArmor annotations == //
 func appArmorAnnotator(pod *corev1.Pod) {
 	podAnnotations := map[string]string{}
+	var podOwnerName string
+
+	// podOwnerName is the pod name for static pods and parent object's name
+	// in other cases
+	for _, ownerRef := range pod.ObjectMeta.OwnerReferences {
```
Comment (nyrahul) [inline pkg/KubeArmorAnnotation/handlers/pod_mutation.go:121]: Can we use the newly created `GetControllingPodOwner()` to replace this loop?

**Review by nyrahul — CHANGES_REQUESTED** [review]

**Review by nyrahul — APPROVED** [review]

File: pkg/KubeArmorAnnotation/handlers/pod_mutation.go (hunk 6 above)
Comment (DelusionalOptimist) [reply pkg/KubeArmorAnnotation/handlers/pod_mutation.go:121]: I couldn't find any example where we were using something from kubearmor's packages in any of the controllers so doing it here kind of felt like an anti-pattern.
Also, the annotations controller and kubearmor use different k8s API versions so we'll have to update the API version used in the controller if we import something or we'll face bugs while building. I thought it would further complicate this PR :sweat_smile:
