### PR TITLE
fix(core): Handle K8s service account token rotation

### LINKED ISSUE #2262: KubeArmor daemonset losing auth. to K8s API after 24 hours
## Bug Report

**General Information**

- Environment description
  EKS 1.34
- Kernel version (run `uname -a`)
  6.12.53
- Orchestration system version in use (e.g. `kubectl version`, ...)

```
Client Version: v1.34.1
Kustomize Version: v5.7.1
Server Version: v1.34.1-eks-3cfe0ce
```

- KubeArmor image versions:
  kubearmor/kubearmor:v1.6.4
  kubearmor/kubearmor-operator:v1.6.4
  kubearmor/kubearmor-controller:v1.6.4

**To Reproduce**

1. Leave nodes/pods running for 24 hours without restart
2. `kuberarmor-bpf-containerd` starts failing to talk to K8s API server

```
2025-11-20T09:19:47.028183113Z 2025-11-20 09:19:47.027933       INFO    Detected a Pod (modified/en-phpin1/deployment-56b7dccf6c-8lnbw)
2025-11-20T09:19:47.028924548Z 2025-11-20 09:19:47.028233       INFO    Updating container rules for 4c4d5f7c9fe957338c7de1442f2e806cc798937e16c6db91d77a0266a73b0c24
2025-11-20T09:19:47.028946252Z 2025-11-20 09:19:47.028698       INFO    Updating container preset rules for 4c4d5f7c9fe957338c7de1442f2e806cc798937e16c6db91d77a0266a73b0c24
2025-11-20T09:19:47.028951593Z 2025-11-20 09:19:47.028721       INFO    [ProtectProc] deleting container with id to protectProc_map exec map: 4c4d5f7c9fe957338c7de1442f2e806cc798937e16c6db91d77a0266a73b0c24
2025-11-20T09:19:47.029000122Z 
2025-11-20T09:19:47.103994428Z 2025-11-20 09:19:47.101607       INFO    Detected a Pod (modified/en-phpin1/deployment-56b7dccf6c-8lnbw)
2025-11-20T09:19:47.104569486Z 2025-11-20 09:19:47.104437       INFO    Updating container rules for 4c4d5f7c9fe957338c7de1442f2e806cc798937e16c6db91d77a0266a73b0c24
2025-11-20T09:19:47.105469231Z 2025-11-20 09:19:47.105322       INFO    Updating container preset rules for 4c4d5f7c9fe957338c7de1442f2e806cc798937e16c6db91d77a0266a73b0c24
2025-11-20T09:19:47.105490953Z 2025-11-20 09:19:47.105418       INFO    [ProtectProc] deleting container with id to protectProc_map exec map: 4c4d5f7c9fe957338c7de1442f2e806cc798937e16c6db91d77a0266a73b0c24
2025-11-20T09:19:47.105495806Z 
2025-11-20T13:43:25.375299118Z E1120 13:43:25.374486       1 reflector.go:205] "Failed to watch" err="Unauthorized" logger="UnhandledError" reflector="pkg/mod/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:290" type="*v1.Namespace"
2025-11-20T13:43:26.590440714Z E1120 13:43:26.590245       1 reflector.go:205] "Failed to watch" err="failed to list *v1.Namespace: Unauthorized" logger="UnhandledError" reflector="pkg/mod/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:290" type="*v1.Namespace"
2025-11-20T13:43:28.307964932Z E1120 13:43:28.307785       1 reflector.go:205] "Failed to watch" err="failed to list *v1.Namespace: Unauthorized" logger="UnhandledError" reflector="pkg/mod/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:290" type="*v1.Namespace"
2025-11-20T13:43:34.136778676Z E1120 13:43:34.136435       1 reflector.go:205] "Failed to watch" err="failed to list *v1.Namespace: Unauthorized" logger="UnhandledError" reflector="pkg/mod/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:290" type="*v1.Namespace"
2025-11-20T13:43:42.573943098Z E1120 13:43:42.573719       1 reflector.go:205] "Failed to watch" err="failed to list *v1.Namespace: Unauthorized" logger="UnhandledError" reflector="pkg/mod/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:290" type="*v1.Namespace"
2025-11-20T13:44:02.467238219Z E1120 13:44:02.467012       1 reflector.go:205] "Failed to watch" err="failed to list *v1.Namespace: Unauthorized" logger="UnhandledError" reflector="pkg/mod/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:290" type="*v1.Namespace"
2025-11-20T13:44:31.056079974Z E1120 13:44:31.055933       1 reflector.go:205] "Failed to watch" err="failed to list *v1.Namespace: Unauthorized" logger="UnhandledError" reflector="pkg/mod/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:290" type="*v1.Namespace"
2025-11-20T13:44:40.423119129Z E1120 13:44:40.422963       1 reflector.go:205] "Failed to watch" err="Unauthorized" logger="UnhandledError" reflector="pkg/mod/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:290" type="*v1.ConfigMap"
2025-11-20T13:44:41.762197838Z E1120 13:44:41.761988       1 reflector.go:205] "Failed to watch" err="failed to list *v1.ConfigMap: Unauthorized" logger="UnhandledError" reflector="pkg/mod/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:290" type="*v1.ConfigMap"
2025-11-20T13:44:44.477953149Z E1120 13:44:44.477769       1 reflector.go:205] "Failed to watch" err="failed to list *v1.ConfigMap: Unauthorized" logger="UnhandledError" reflector="pkg/mod/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:290" type="*v1.ConfigMap"
2025-11-20T13:44:50.226514840Z E1120 13:44:50.226360       1 reflector.go:205] "Failed to watch" err="failed to list *v1.ConfigMap: Unauthorized" logger="UnhandledError" reflector="pkg/mod/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:290" type="*v1.ConfigMap"
2025-11-20T13:45:02.588369054Z E1120 13:45:02.588220       1 reflector.go:205] "Failed to watch" err="failed to list *v1.ConfigMap: Unauthorized" logger="UnhandledError" reflector="pkg/mod/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:290" type="*v1.ConfigMap"
2025-11-20T13:45:21.045027095Z E1120 13:45:21.044821       1 reflector.go:205] "Failed to watch" err="failed to list *v1.ConfigMap: Unauthorized" logger="UnhandledError" reflector="pkg/mod/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:290" type="*v1.ConfigMap"
2025-11-20T13:45:26.324700354Z E1120 13:45:26.324403       1 reflector.go:205] "Failed to watch" err="failed to list *v1.Namespace: Unauthorized" logger="UnhandledError" reflector="pkg/mod/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:290" type="*v1.Namespace"
2025-11-20T13:45:50.719804507Z E1120 13:45:50.719638       1 reflector.go:205] "Failed to watch" err="failed to list *v1.ConfigMap: Unauthorized" logger="UnhandledError" reflector="pkg/mod/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:290" type="*v1.ConfigMap"
2025-11-20T13:45:56.868497779Z E1120 13:45:56.868362       1 reflector.go:205] "Failed to watch" err="Unauthorized" logger="UnhandledError" reflector="pkg/mod/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:290" type="*v1.Node"
...
```

Full container log: [kubearmor-bpf-containerd.log](https://github.com/user-attachments/files/23657372/kubearmor-bpf-containerd.log)

3. restart pod fixes the issue

**Expected behavior**

KubeArmor daemonset periodically reloads credentials from `/var/run/secrets/kubernetes.io/serviceaccount`, or at least is able to reconnect.

### PR DESCRIPTION
**Pull request by AryanBakliwal**
**Purpose of PR?**:

1. Previously, client config when running in-cluster and using kubeconfig was created separately. This PR uses `GetConfigOrDie` from `sigs.k8s.io/controller-runtime` which automatically creates the config depending on where it is running, and also takes care of refreshing the token after rotation.
2. Creates HTTP rest client from config, which now removes the need to run kubectl proxy when developing locally as authentication is handled by the client.

Fixes #2262 

**Does this PR introduce a breaking change?**
No

**If the changes in this PR are manually verified, list down the scenarios covered:**
Using a local k3s cluster and setting token expiration time to 1 hour. See timestamp in logs:

**Before**
After ~1 hour, the token expires and requests to API server return unauthorized
```
$ kubectl logs -n kubearmor kubearmor-bpf-containerd-2c350-5z8tf 

2026-03-12 16:46:35.651297	INFO	BUILD-INFO: version: v1.6.8-dirty, branch: HEAD, date: 2026-02-04T09:57:14Z
...
2026-03-12 16:46:35.659895	INFO	Initialized Kubernetes client
...
2026-03-12 17:48:03.890848	INFO	[ProtectProc] deleting container with id to protectProc_map exec map: 708e36794693dde1bc8b2cec90830e08b4ccd26ca76811c3c35cab95157beb27

E0312 17:48:33.107939       1 reflector.go:205] "Failed to watch" err="failed to list *v1.ConfigMap: Unauthorized" logger="UnhandledError" reflector="pkg/mod/k8s.io/client-go@v0.34.1/tools/cache/reflector.go:290" type="*v1.ConfigMap"
E0312 17:49:25.584014       1 reflector.go:205] "Failed to watch" err="failed to list *v1.ConfigMap: Unauthorized"
...
```

**After**
KubeArmor pod running for >1.5 hour, working as expected
```
$ kubectl get pods -n kubearmor                                                                                                                                   

NAME                                    READY   STATUS    RESTARTS   AGE
kubearmor-bpf-containerd-2c350-d4jzf    1/1     Running   0          91m
kubearmor-controller-6cff7cdcb8-gx9d9   1/1     Running   0          91m
kubearmor-operator-574f9967ff-hkx65     1/1     Running   0          93m
kubearmor-relay-6f5445f967-nt89m        1/1     Running   0          92m
```
```
$ kubectl logs -f -n kubearmor kubearmor-bpf-containerd-2c350-d4jzf

2026-03-12 18:30:19.219019	INFO	BUILD-INFO: version: v1.6.14-dirty, branch: fix-sa-token-rotation, date: 2026-03-12T17:56:24Z
...
2026-03-12 18:30:19.221908	INFO	Initialized Kubernetes client
...
2026-03-12 20:04:03.864832	INFO	Namespace pentestit visibiliy configured {File:true Process:true Network:true Capabilities:true DNS:false IMA:false}
```

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [x] Bug fix. Fixes #2262 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Review by rksharma95 — DISMISSED** [review]

File: KubeArmor/core/k8sHandler.go [hunk 1]
```diff
@@ -153,16 +153,19 @@ func (kh *K8sHandler) InitLocalAPIClient() error {
 
 // InitInclusterAPIClient Function
 func (kh *K8sHandler) InitInclusterAPIClient() error {
```
Comment (achrefbensaad) [inline KubeArmor/core/k8sHandler.go]: I think we should drop this and use SDK to handle. Lets discuss on our sync will demo the plan

**Review by achrefbensaad — DISMISSED** [review]

**Review by rksharma95 — APPROVED** [review]

**Review by Aryan-sharma11 — APPROVED** [review]
