### PR TITLE
Default Posture logs bug

### LINKED ISSUE #1250: Default Posture logs are getting shown up after block policy application
## Bug Report
When I apply the following Vault Policy in my AKS cluster I am getting this default posture logs 
```sh
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-vault-protect
  namespace: default
spec:
  severity: 7
  selector:
    matchLabels:
      app.kubernetes.io/name: vault
      component: server
  file:
    matchDirectories:
    - dir: /vault/
      recursive: true
      action: Block
    - dir: /
      recursive: true
    - dir: /vault/
      recursive: true
      fromSource:
      - path: /bin/vault
  process:
    matchPaths:
    - path: /bin/busybox
    - path: /bin/vault
  action: Allow
  message: 'Vault Hardening Policy '
```

I am getting this default posture logs : 

```sh 
Action:Audit
ClusterName:azure-demo-cluster
ContainerID:d9c9959dcba6bc67d5124bc12eacd15cc617187716be17a9fee44682eef71878
ContainerImage:docker.io/hashicorp/vault:1.13.1@sha256:b888abc3fc0529550d4a6c87884419e86b8cb736fe556e3e717a6bc50888b3b8
ContainerName:vault
Data:syscall=SYS_OPENAT fd=-100 flags=O_RDONLY
Enforcer:eBPF Monitor
HostName:aks-agentpool-36168086-vmss000003
HostPID:2866379
HostPPID:2845784
Labels:component=server,helm.sh/chart=vault-0.24.1,statefulset.kubernetes.io/pod-name=vault-0,app.kubernetes.io/instance=vault,app.kubernetes.io/name=vault
NamespaceName:default
Operation:File
PID:1774
PPID:2845784
ParentProcessName:/usr/bin/containerd-shim-runc-v2
PodName:vault-0
PolicyName:DefaultPosture
ProcessName:/bin/vault
Resource:/sys/kernel/mm/transparent_hugepage/hpage_pmd_size
Result:Passed
Source:/bin/vault status -tls-skip-verify
Timestamp:1685458455
Type:MatchedPolicy
UID:100
UpdatedTime:2023-05-30T14:54:15.873859Z
cluster_id:369
component_name:kubearmor
instanceGroup:0
instanceID:0
tenant_id:11
```

### PR DESCRIPTION
**Pull request by Aryan-sharma11**
**Purpose of PR?**:

Fixes #1250 

**Does this PR introduce a breaking change?**
No
**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**In the current design for `Operation == File/Process` we follow  the following design.**
image

**what this PR introduces is, a new check for checking if the log is matched earlier. So it won't overwrite the action according to `File default posture` while checking other rules.**

**Checklist:**
- [x] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

File: KubeArmor/feeder/policyMatcher.go [hunk 1]
```diff
@@ -1183,8 +1182,7 @@ func (fd *Feeder) UpdateMatchedPolicy(log tp.Log) tp.Log {
 					log.Action = "Audit (Block)"
 				}
 
-				if fd.DefaultPostures[log.NamespaceName].FileAction == "audit" && (secPolicy.Action == "Allow" || secPolicy.Action == "Audit (Allow)") && log.Result == "Passed" {
-					// defaultPosture = audit
```
Comment (daemon1024) [inline KubeArmor/feeder/policyMatcher.go:1187]: Let's keep this comment.

And also, let's add a commet that we only apply default posture whe log.type isn't yet known.

**Review by daemon1024 — CHANGES_REQUESTED** [review]
Thanks for fixing the bug, the changes make sense to me 👌🏽

**Review by daemon1024 — APPROVED** [review]

**Review by nyrahul — APPROVED** [review]
