### PR TITLE
fix(monitor): handle logs with process name empty

### LINKED ISSUE #1931: system monitor policyMatcher allows telemetry with empty processName
## Bug Report

**General Information**

- Environment description: `k3s v1.30.6+k3s1`
- Kernel version (run `uname -a`): `6.6.63-1-lts`
- Orchestration system version in use (e.g. `kubectl version`, ...)
  ```
  Client Version: v1.30.6+k3s1
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  Server Version: v1.30.6+k3s1
  ```
- Link to relevant artifacts (policies, deployments scripts, ...)
- Target containers/pods

**To Reproduce**
- to replicate the behaviour modify kubearmor to ignore `/usr/bin/date` 
  ```
  if path == "/usr/bin/date" {
    return ""
  }
  ```
https://github.com/kubearmor/KubeArmor/blob/f3902690c2a03ffb4df49a7c153ff3ba5f64cb3c/KubeArmor/monitor/processTree.go#L273
https://github.com/kubearmor/KubeArmor/blob/f3902690c2a03ffb4df49a7c153ff3ba5f64cb3c/KubeArmor/monitor/processTree.go#L300

- deploy nginx deployment 
  ```
  kubectl create deployment nginx --image=nginx
  ```
- apply ksp
  ```
  apiVersion: security.kubearmor.com/v1
  kind: KubeArmorPolicy
  metadata:
    name: ksp-nginx-allow-bin-dir-process
  spec:
    action: Allow
    process:
      matchDirectories:
      - dir: /bin/
        recursive: true
    selector:
      matchLabels:
        app: nginx
  ```
- observe kubearmor telemetry in a seperate terminal
  ```
  karmor logs
  ```
- execute inside nginx pod
  ```
  /usr/bin/date +%Y-%m-%d %H:%M:%S
  ```
**Expected behavior**

if processName is empty, telemetry should use source information as processName

**Screenshots**
Screenshot From 2025-01-03 10-11-26

ProcessName is not present in the telemetry.

### PR DESCRIPTION
**Pull request by rksharma95**
**Purpose of PR?**:

Fixes #1931 

**Does this PR introduce a breaking change?**

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [x] Bug fix. Fixes #1931 
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

File: KubeArmor/feeder/feeder.go [hunk 1]
```diff
@@ -556,6 +556,10 @@ func (fd *Feeder) PushLog(log tp.Log) {
 			return
 		}
 		fd.Debug("Pushing Telemetry without source")
+	} else {
+		if log.ProcessName == "" {
+			log.ProcessName = log.Source
+		}
 	}
```
Comment (daemon1024) [inline KubeArmor/feeder/feeder.go]: This needs to happen before Policy Matcher. Consider doing it in System Monitor itself.

**Review by daemon1024 — CHANGES_REQUESTED** [review]

File: KubeArmor/monitor/logUpdate.go [hunk 2]
```diff
@@ -524,6 +524,15 @@ func (mon *SystemMonitor) UpdateLogs() {
 				continue
 			}
 
+			if log.ProcessName == "" {
+				switch log.Operation {
+				case "Process":
+					log.ProcessName = strings.Split(log.Resource, " ")[0]
```
Comment (daemon1024) [inline KubeArmor/monitor/logUpdate.go]: Do we need to verify log.Resource and log.Source is empty? If it can be empty, this can cause runtime panic.

Comment (rksharma95) [reply KubeArmor/monitor/logUpdate.go]: for the cases where process name as well as source/resource is empty. should we drop that event? similar to: https://github.com/kubearmor/KubeArmor/blob/59ac3021b43cf3d05d4c55b6a372dbfde39a10ec/KubeArmor/feeder/feeder.go#L554

**Review by Prateeknandle — APPROVED** [review]
LGTM

**Review by daemon1024 — APPROVED** [review]
