### PR TITLE
fix(tests): Use enforcer-agnostic annotation in tests

### LINKED ISSUE #1129: ginkgo tests should work with BPF LSM
**Short Description**

We use ginkgo for running tests locally as well as in CI. However, currently they depend on Apparmor annotations of the test workload for validation.
We should modify the tests accordingly so that they work with BPF LSM as well.

### PR DESCRIPTION
**Pull request by rksharma95**
**Purpose of PR?**:
At this point the ginkgo tests are implemented in such a way that they will work only if current enforcer is AppArmor due to the dependency on AppArmor annotations. Merging this PR will enable the tests to work with bpflsm enforcer too.

_As GH action doesn't support enabling bpflsm for now this fix will enable users do testing locally with KubeArmor running as system process._
Fixes #1129 

**Does this PR introduce a breaking change?**
No
**If the changes in this PR are manually verified, list down the scenarios covered:**:
tested for both AppArmor and BPFLSM enforcer, able to run the tests in both scenarios.
**Additional information for reviewer?** :
_Mention if this PR is part of any design or a continuation of previous PRs_

**Checklist:**
- [x] Bug fix. Fixes #<issue number>
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`

### CODE REVIEW

**Review by DelusionalOptimist — COMMENTED** [review]
Thank you for working on this @rksharma95. Looks good to me. :rocket:
Just have to fix the gosec issue.

**Comment by DecFox** [comment]
Hey @rksharma95, is there a specific reason why the `WriteToFile` permissions have been elevated here? (since it is the reason for the failing go-sec)

**Comment by rksharma95** [comment]
> Hey @rksharma95, is there a specific reason why the `WriteToFile` permissions have been elevated here? (since it is the reason for the failing go-sec)

to read current enforcer info from the probe data, as tests are allowed to run as non-root user, in fact we are running the tests as non-root user at present.

File: tests/util/kartutil.go [hunk 1]
```diff
@@ -295,10 +300,41 @@ func K8sExecInPodWithContainer(pod string, ns string, container string, cmd []st
 	return buf.String(), errBuf.String(), nil
 }
 
+func isBpfLsmEnforcer() (bool, error) {
+	if _, err := os.Stat("/tmp/karmorProbeData.cfg"); err != nil {
+		log.Errorf("unable to karmorProbeData.cfg: %s", err)
+		return false, nil
```
Comment (daemon1024) [inline tests/util/kartutil.go]: We don't use host process mode but deploy kubearmor on k8s in tests. Not sure if this would work. We should add the check to extract as well maybe?

**Comment by Aryan-sharma11** [comment]
Is this PR ready to be merged? @rksharma95

**Comment by rksharma95** [comment]
> Is this PR ready to be merged? @rksharma95

no, there's still some pending task.

**Comment by rksharma95** [comment]
rather than checking enforcer specific annotations, can we check of some enforcer-agnostic annotations i.e. `kubearmor-policy: enabled` to ensure that the pod has been processed by the kubearmor. 

any thoughts here? @daemon1024

**Review by daemon1024 — APPROVED** [review]
LGTM

**Review by DelusionalOptimist — COMMENTED** [review]
@rksharma95 I think we missed the visibility test suite. :eyes:

**Review by DelusionalOptimist — APPROVED** [review]
LGTM. Thanks sticking with this @rksharma95 : )

**Comment by DelusionalOptimist** [comment]
Also, thank you @DecFox, @Aryan-sharma11 for probing into this PR. :raised_hands:
