### PR TITLE
 fix(core): ensure only cluster policy is updated on new ns

### LINKED ISSUE #1780: Kubearmor fetches wrong pod name/namespace to apply whitelist policy on long running GKE clusters (BPF-LSM enforcement)
## Bug Report

**General Information**

## Issue
This is a consistent issue when running kubearmor on any long-lived cluster. We have a set of policies in `protected-namespace` where we whitelist only a few pods based on labels:
### Config
```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: default-deny
  namespace: protected-namespace
spec:
  action: Block
  process:
    matchDirectories:
    - dir: /
      recursive: true
  selector:
    matchLabels: {}
---
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: allow-app
  namespace: protected-namespace
spec:
  action: Allow
  file:
    matchDirectories:
    - dir: /
      recursive: true
  process:
    matchDirectories:
    ## list of matchDirectories here
    matchPaths:
    ## list of allowed paths here
  selector:
    matchLabels:
      kubearmor-whitelist-profile: app
```
### Symptom
A pod from `unprotected-namespace` cannot run due to not being able to run `correct-binary: permission-denied`

### Extra information
With this configuration, after a time with kubearmor running on cluster, kubearmor starts to deny applications in `unprotected-namespaces` as well, even though there are no `KubearmorPolicy` objects on these namespace:

From karmor logs, I could see:
```
{
"Timestamp":1718029258,
"UpdatedTime":"2024-06-10T14:20:58.078820Z",
"ClusterName":"default",
"HostName":"***-bz88",
"NamespaceName":"protected",
"Owner":{"Ref":"Pod","Name":"wrong-pod-name","Namespace":"protected"},
"PodName":"wrong-pod-name",
"Labels":"wrong-pod-labels",
"ContainerID":"wrong-id",
"ContainerName":"wrong-container",
"ContainerImage":"wrong-image",
"ProcessName":"/binary-from-unprotected-pod",
"PolicyName":"default-deny",
"Severity":"1",
"Type":"MatchedPolicy",
"Operation":"Process",
"Resource":"/binary-from-unprotected-pod",
"Data":"lsm=SECURITY_BPRM_CHECK",
"Enforcer":"BPFLSM",
"Action":"Block",
"Result":"Permission denied",
"Cwd":"/"
}
```
This is recurring on any clsuter we have kubearmor operator running. As a workaround, if we `kubectl delete pods --all -n <kubearmor-namespace>`, the system goes back to running as expected (until a few days/weeks later, the issue restarts).

### Versions
Kubearmor: `v1.3.4`
Cluster: gke `1.27.13-gke.1000000`

**Expected behavior**

I would expect kubearmor to consistently get the information of the correct pods' names and namespaces :).

### LINKED ISSUE #1840: Container policies incorrectly applied at cluster level
## Bug Report

**General Information**

This is happening in AWS EKS.
K8s version: v1.28.11-eks-db838b0.
KubeArmor: v1.4.0.
Kernel: 5.10.217-205.860.amzn2.x86_64

**To Reproduce**

A very simple policy:

```
apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: generic-maint-tools-access
  namespace: myapplication
spec:
  action: Audit
  message: Restricted maintenance tool access attempt detected
  process:
    matchDirectories:
      - dir: /sbin/
        recursive: true
      - dir: /usr/sbin/
        recursive: true
  selector:
    matchLabels:
      security: generic
  severity: 1
  tags:
    - PCI_DSS
    - MITRE
    - MITRE_T1553_Subvert_Trust_Controls
```

All bpf-containerd pods log this:

```
Detected a Security Policy (added/myapplication/generic-maint-tools-access)
```

However, a few hours later, I get these logs:

```
{
...
  "NamespaceName": "anothernamespace",
  "Owner":
    { "Ref": "StatefulSet", "Name": "somests", "Namespace": "anothernamespace" },
  "PodName": "somepod-2",
  "Labels": "...",
  "ContainerID": "...",
  "ContainerName": "somecontainername",
  "ContainerImage": "...",
  "HostPPID": ...,
  "HostPID": ...,
  "PPID": ...,
  "PID": ...,
  "UID": ...,
  "ParentProcessName": "...",
  "ProcessName": "...",
  "PolicyName": "generic-maint-tools-access",
  "Severity": "1",
  "Tags": "PCI_DSS,MITRE,MITRE_T1553_Subvert_Trust_Controls",
  "ATags": ["PCI_DSS", "MITRE", "MITRE_T1553_Subvert_Trust_Controls"],
  "Message": "Restricted maintenance tool access attempt detected",
  "Type": "MatchedPolicy",
  "Source": "....",
  "Operation": "Process",
  "Resource": "...",
  "Data": "syscall=SYS_EXECVE",
  "Enforcer": "eBPF Monitor",
  "Action": "Audit",
  "Result": "Passed",
  "Cwd": "/",
  ...
}
```

I have no other policy named `generic-maint-tools-access` in any other namespace, or cluster policy named like that.

**Expected behavior**

Container policies are not incorrectly applied to other namespaces.

**Screenshots**

### PR DESCRIPTION
**Pull request by carlosrodfern**
Regular policies are mistakenly modified and applied at cluster level over time

**Purpose of PR?**:

Fixes: #1840

**Does this PR introduce a breaking change?** No

**If the changes in this PR are manually verified, list down the scenarios covered:**:
Built and deployed, and verified that the policy is not applied on different namespaces or even the same namespace with no matching labels.

**Additional information for reviewer?** :

**Checklist:**
- [x] Bug fix. Fixes #1840
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

File: KubeArmor/core/kubeUpdate.go [hunk 1]
```diff
@@ -959,48 +959,6 @@ func (dm *KubeArmorDaemon) WatchK8sPods() {
 	}
 }
 
-func matchClusterSecurityPolicyRule(policy tp.SecurityPolicy) bool {
-	hasInOperator := false
```
Comment (Prateeknandle) [inline KubeArmor/core/kubeUpdate.go:963]: 1. we should not remove `matchClusterSecurityPolicyRule()`, reason is mentioned [here](https://github.com/kubearmor/KubeArmor/issues/1780#issuecomment-2288151891).
2. let's add a check :
```
if len(policy.Spec.Selector.Identities) >0 {
		return false
	}
```
this would indicate that the policy is a `KubeArmorSecurityPolicy`, and not the cluster policy.

Comment (Prateeknandle) [reply KubeArmor/core/kubeUpdate.go:963]: cc : @daemon1024

Comment (carlosrodfern) [reply KubeArmor/core/kubeUpdate.go:963]: I have updated the commit. Thank you @Prateeknandle!

**Review by Prateeknandle — APPROVED** [review]
Thanks @carlosrodfern for this quick fix.

**Review by DelusionalOptimist — APPROVED** [review]
LGTM. Thanks @carlosrodfern! :raised_hands:
