### PR TITLE
[bug] Fixed the panic for uninitialized docker daemon

### LINKED ISSUE #1948: KubeArmor Panic if uninitialised docker socket exists
## Bug Report

KubeArmor Panic if uninitialised docker socket exists

**General Information**

https://github.com/kubearmor/KubeArmor/blob/88f54a60269f81fca059ae81a67b2abe35ea047c/KubeArmor/core/dockerHandler.go#L265-L271

We don't do a return if there's an error while initialising. This creates a panic because we call the client function with a nil client. We should return early from the function.

- Environment description (ubuntu 18.04)
- Orchestration system version in use (unorchestrated)

**To Reproduce**

Have the docker socket file exist, but the docker daemon would be down
KubeArmor Panics on init

**Expected behavior**

No panic

Panic Trace

```
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]: 2025-01-21 02:40:15.673868        INFO        Verifying Docker API client version: 1.44
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]: 2025-01-21 02:40:15.673994        ERROR        Failed to create new Docker client: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]: github.com/kubearmor/KubeArmor/KubeArmor/log.Err
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]:         /home/runner/work/KubeArmor/KubeArmor/KubeArmor/log/logger.go:103
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]: github.com/kubearmor/KubeArmor/KubeArmor/feeder.(*Feeder).Errf
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]:         /home/runner/work/KubeArmor/KubeArmor/KubeArmor/feeder/feeder.go:446
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]: github.com/kubearmor/KubeArmor/KubeArmor/core.(*KubeArmorDaemon).GetAlreadyDeployedDockerContainers
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]:         /home/runner/work/KubeArmor/KubeArmor/KubeArmor/core/dockerHandler.go:265
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]: github.com/kubearmor/KubeArmor/KubeArmor/core.KubeArmor
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]:         /home/runner/work/KubeArmor/KubeArmor/KubeArmor/core/kubeArmor.go:585
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]: main.main
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]:         /home/runner/work/KubeArmor/KubeArmor/KubeArmor/main.go:79
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]: runtime.main
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]:         /home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.12.linux-amd64/src/runtime/proc.go:267
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19e0035]
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]: goroutine 1 [running]:
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]: github.com/kubearmor/KubeArmor/KubeArmor/core.(*KubeArmorDaemon).GetAlreadyDeployedDockerContainers(0xc00015b800)
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]:         /home/runner/work/KubeArmor/KubeArmor/KubeArmor/core/dockerHandler.go:269 +0xb5
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]: github.com/kubearmor/KubeArmor/KubeArmor/core.KubeArmor()
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]:         /home/runner/work/KubeArmor/KubeArmor/KubeArmor/core/kubeArmor.go:585 +0x1365
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]: main.main()
Jan 21 02:40:15 ip-172-31-28-212 kubearmor[6963]:         /home/runner/work/KubeArmor/KubeArmor/KubeArmor/main.go:79 +0x3ed
Jan 21 02:40:17 ip-172-31-28-212 systemd[1]: kubearmor.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 21 02:40:17 ip-172-31-28-212 systemd[1]: kubearmor.service: Failed with result 'exit-code'.
Jan 21 02:40:27 ip-172-31-28-212 systemd[1]: kubearmor.service: Service hold-off time over, scheduling restart.
Jan 21 02:40:27 ip-172-31-28-212 systemd[1]: kubearmor.service: Scheduled restart job, restart counter is at 6.
Jan 21 02:40:27 ip-172-31-28-212 systemd[1]: Stopped KubeArmor.
Jan 21 02:40:27 ip-172-31-28-212 systemd[1]: Started KubeArmor.
```

### PR DESCRIPTION
**Pull request by Manik2708**
**Purpose of PR?**:

Fixes #1948 

**Does this PR introduce a breaking change?** No

**If the changes in this PR are manually verified, list down the scenarios covered:**:

**Additional information for reviewer?** :
cc @daemon1024 I am not able to reproduce the error, please can you verify whether this change is able to avoid panic or help me in reproducing this panic

**Checklist:**
- [x] Bug fix. Fixes #<issue number>
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] PR Title follows the convention of  `<type>(<scope>): <subject>`
- [ ] Commit has unit tests
- [ ] Commit has integration tests

### CODE REVIEW

**Comment by Manik2708** [comment]
@daemon1024 Please see the description!

File: KubeArmor/core/dockerHandler.go [hunk 1]
```diff
@@ -455,6 +456,7 @@ func (dm *KubeArmorDaemon) GetAlreadyDeployedDockerContainers() {
 	} else {
 		dm.Logger.Warnf("Error while listing containers: %s", err)
```
Comment (Manik2708) [inline KubeArmor/core/dockerHandler.go]: Do this need to terminate `KubeArmorDaemon` also?

**Comment by Manik2708** [comment]
@rksharma95 @Aryan-sharma11 @daemon1024 Please review!

File: KubeArmor/core/kubeArmor.go [hunk 2]
```diff
@@ -621,7 +621,10 @@ func KubeArmor() {
 			// monitor containers
 			if strings.Contains(cfg.GlobalCfg.CRISocket, "docker") {
 				// update already deployed containers
-				dm.GetAlreadyDeployedDockerContainers()
+				err := dm.GetAlreadyDeployedDockerContainers()
+				if err != nil {
+					dm.DestroyKubeArmorDaemon()
```
Comment (Aryan-sharma11) [inline KubeArmor/core/kubeArmor.go]: This might cause issues in systemd installations with no docker socket present. Can we verify it @Manik2708 ?

Comment (Manik2708) [reply KubeArmor/core/kubeArmor.go]: Can you assist little here? What exactly I need to verify?

Comment (Manik2708) [reply KubeArmor/core/kubeArmor.go]: Like I want to ask what should happen when docker socket is not present in systemd? Should it still move forward? As we can't invoke `dm.GetAlreadyDeployedDockerContainers` because it will panic!

Comment (Aryan-sharma11) [reply KubeArmor/core/kubeArmor.go]: Yes, kubearmor should still work as we can have host security policies, but it should not panic looking for container, we can just have some warning to indicate docker is not present.

**Comment by Manik2708** [comment]
@Aryan-sharma11 Have made the changes, please review!

File: KubeArmor/core/kubeArmor.go [hunk 3]
```diff
@@ -663,7 +667,11 @@ func KubeArmor() {
 			// monitor containers
 			if strings.Contains(dm.Node.ContainerRuntimeVersion, "docker") || strings.Contains(cfg.GlobalCfg.CRISocket, "docker") {
 				// update already deployed containers
-				dm.GetAlreadyDeployedDockerContainers()
+				err := dm.GetAlreadyDeployedDockerContainers()
+				if err != nil {
+					dm.DestroyKubeArmorDaemon()
```
Comment (Aryan-sharma11) [inline KubeArmor/core/kubeArmor.go]: let's not destroy kubearmor daemon here

File: KubeArmor/core/kubeArmor.go [hunk 4]
```diff
@@ -691,8 +699,11 @@ func KubeArmor() {
 					cfg.GlobalCfg.CRISocket = "unix://" + socketFile
 
 					// update already deployed containers
-					dm.GetAlreadyDeployedDockerContainers()
-
+					err := dm.GetAlreadyDeployedDockerContainers()
+					if err != nil {
```
Comment (Aryan-sharma11) [inline KubeArmor/core/kubeArmor.go]: let's not destroy kubearmor daemon

File: KubeArmor/core/dockerHandler.go [hunk 5]
```diff
@@ -258,13 +258,14 @@ func (dm *KubeArmorDaemon) SetContainerVisibility(containerID string) {
...
 
 // GetAlreadyDeployedDockerContainers Function
-func (dm *KubeArmorDaemon) GetAlreadyDeployedDockerContainers() {
+func (dm *KubeArmorDaemon) GetAlreadyDeployedDockerContainers() error {
 	// check if Docker exists else instantiate
 	if Docker == nil {
 		var err error
 		Docker, err = NewDockerHandler()
 		if err != nil {
 			dm.Logger.Errf("Failed to create new Docker client: %s", err)
```
Comment (Aryan-sharma11) [inline KubeArmor/core/dockerHandler.go]:
```suggestion
			dm.Logger.Errf("Failed to create new Docker client: %s", err.Error())
```

File: KubeArmor/core/dockerHandler.go [hunk 6]
```diff
@@ -748,6 +750,7 @@ func (dm *KubeArmorDaemon) MonitorDockerEvents() {
...
```
Comment (Aryan-sharma11) [inline KubeArmor/core/dockerHandler.go]:
```suggestion
			dm.Logger.Errf("Failed to create new Docker client: %s", err.Error())
```

**Review by Aryan-sharma11 — CHANGES_REQUESTED** [review]

File: KubeArmor/core/kubeArmor.go (hunk 4 above)
Comment (Manik2708) [reply KubeArmor/core/kubeArmor.go]: Then I think we need to trace the usage of docker client as it will panic again if used (if nil)

Comment (Aryan-sharma11) [reply KubeArmor/core/kubeArmor.go]: > Then I think we need to trace the usage of docker client as it will panic again if used (if nil)

Sorry, I didn't understand wat do you meant by the need to trace, can you give some example or screenshot?
The purpose of keeping this error as a warning and not stopping `kubearmor.service` is that kubearmor can still enforce host security policies, even if docker is not present. We also have a flag to enable/disable the enforcement on containers `enablekubearmorpolicy`. In my opinion, we can keep showing this in warning until the docker daemon starts.

Comment (Manik2708) [reply KubeArmor/core/kubeArmor.go]: Sorry for the late reply as I was caught in my exams. So by trace I meant to say that we need to ensure that if docker client is nil we need to ensure that it is not used after that. I observed that this was also happening in one of the another functions also, like: `MonitorDockerEvents`

Comment (Aryan-sharma11) [reply KubeArmor/core/kubeArmor.go]: Yes, please add the handling for that case also, but destroying the daemon is not the way to go.

**Comment by Manik2708** [comment]
@Aryan-sharma11 Really sorry for the long wait, kindly review. I think if we don't want to destroy the daemon, then just returning on error will be enough. Please provide your suggestions to this!

**Review by daemon1024 — APPROVED** [review]

**Review by Aryan-sharma11 — APPROVED** [review]

**Comment by Manik2708** [comment]
@Aryan-sharma11 @daemon1024 Cleaned the commit history! Please review!
